### ISSUE TITLE
testing files missing

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#114]
In the "Testing" section of the files /opt/online/loleaflet/README, you can find several pages to access.

But when I tried them, I have a white page and in the logs, lines about resources not found (.js and .css files)

Ie:
- to run the unit tests
      + open spec/loleaflet.html in the browser
```
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.523908 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.524402 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.591102 [ websrv_poll ] WRN  #26: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.591588 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.703774 [ websrv_poll ] WRN  #24: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.704586 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.706024 [ websrv_poll ] WRN  #19: Failed to stat [/opt/online//loleaflet/dist/dialog/vex-theme-plain.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.707155 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex-theme-plain.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.708641 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.709229 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.724069 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.724492 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.738981 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:35:00 lool loolwsd[1712]: wsd-01712-01722 16:35:00.739627 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| wsd/FileServer.cpp:274
```
- to simulate an editing session and to get the tile loading times
        + open spec/tilebench.html in the browser
```
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.008717 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.009314 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.013067 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.013609 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.015291 [ websrv_poll ] WRN  #19: Failed to stat [/opt/online//loleaflet/dist/dialog/vex-theme-plain.css]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.015807 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex-theme-plain.css]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.018683 [ websrv_poll ] WRN  #19: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.019497 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.021453 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.022167 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.024576 [ websrv_poll ] WRN  #19: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.combined.min.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.025370 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.combined.min.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.075485 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.076067 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/mocha/mocha.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.101540 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.102765 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/node_modules/happen/happen.js]. File will not be sent.| wsd/FileServer.cpp:274
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.129199 [ websrv_poll ] WRN  #15: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.combined.min.js]. File will not be sent.| net/Socket.cpp:211
Aug 11 18:37:36 lool loolwsd[1712]: wsd-01712-01722 16:37:36.129845 [ websrv_poll ] ERR  FileServerRequestHandler: File not found: Failed to stat [/opt/online//loleaflet/dist/dialog/vex.combined.min.js]. File will not be sent.| wsd/FileServer.cpp:274
```

**Comment by aalaesar** [comment]
Hi 😄 
Did you enabled debug for loolwsd ?
This remind me of an error I had with another branch of online
What was the branch set used by the script ? (this info is given in the script's logs on the first lines of preparation.log) ?
Regards.

**Comment by quenenni** [comment]
I didn't enable the debug mode. But I fail to see why I need it to have access to these files.
The errors seem to say the files / folders aren't physically present.

Unfortunately, I deleted that server and started a new installation. I don't have that info anymore and I can't go check if indeed the files are missing (I know, I should have done that)

I'll check with the debug mode when it will be finished.

I had the same situation 2 days ago when I succeeded with my debian 8 (was it the same branch??).

**Comment by aalaesar** [comment]
Opening/reading from the server's filesystem is now disabled by default. see #99 
To allow it again you need to set `<filesystem allow="true" />` at line 71 in loolwsd.xml and restart loolwsd.
This option can be a security risk if your server is available online. see #93.
But i'm not sure if the errors are linked to this restriction.

**Comment by quenenni** [comment]
Ho, that's the debug option.
Then, it was enabled 
I added this option "--o:storage.filesystem[@Allow]=true" in the file  /etc/systemd/system/loolwsd.service in order to test an example file (/loleaflet/dist/loleaflet.html?file_path=file:///opt/online/test/data/hello.odt)

I have the feeling they are just missing. I'll tell you what as soon as I have finished this compilation.

**Comment by Kassiematis** [comment]
Don't forget to change this in officeonline-install.cfg

lool_configure_opts='--enable-debug'

**Comment by quenenni** [comment]
I check the compiled code, I searched the filesystem for those missing files / folders but weren't there.

I went on the lool github repo and there also, these missing folders / files aren't present (https://github.com/LibreOffice/online/tree/master/loleaflet).

Sooo.. I guess they removed them but forgot about the test files depending on them.
I'll create a ticket there.

@Kassiematis Unfortunately, I saw your answer after I started the process, so I didn't added that option.

But what exactly does it do? Is it different from the ""--o:storage.filesystem[@Allow]=true" option?


EDIT: Ho crap.. It's not possible to create a new ticket in the Lool github repo. Do you know where I can do that?

**Comment by aalaesar** [comment]
@quenenni 
Just tested my hypothesis: the test files are created when running the build using the '--enable-debug' option
I had already loolwsd built on my test machine with most of the default configuration. I checked that the test files where missing (they where).
I ran again the script with 
`sudo ./officeonlin-install.sh/officeonline-install.sh -c lool_configure_opts='--enable-debug' -f lool`
And once rebuilt, the test files where present. 😉

**Comment by quenenni** [comment]
Nice.

Do you want me to have them in order to have access to these test files and have test reports to help you?
Or is it not related?
(I still don't really what kind of debian tests you were talking in the other ticket)

My day was to have HAproxy working.
The HAproxy version from Jessie is working fine, but the same config in the Stretch version doesn't work, and I couldn't find wy..
(if you are interested by a HAproxy config post, I can start one. It's not about this project, but I think lots of people will use smthg like HAproxy in the future)

**Comment by Ark74** [comment]
El 12 de agosto de 2017 2:29:11 PM CDT, quenenni <notifications@github.com> escribió:
>Nice.
>
>Do you want me to have them in order to have access to these test files
>and have test reports to help you?
>Or is it not related?
>(I still don't really what kind of debian tests you were talking in the
>other ticket)
>
>My day was now to have HAproxy working.
>The HAproxy version from Jessie is working fine, but the same config in
>the Stretch version doesn't work, and I could find wy..
>(if you are interested by a HAproxy config post, I can start one. It's
>not about this project, but I think lots of people will use smthg like
>HAproxy in the future)

Why not use the apache or nginx proxy conf?

-- 
Luis

**Comment by aalaesar** [comment]
Testing on debian or any system is frankly just smoke-testing
Running the script. Test if the app work good..not that much.
Indeed the test files are convenient  to test lots of case but we moved on and disabled them.
So now I do test with private files.

For the rest of the service architecture it just up to you 😄
@Ark74 I suppose he can if he want 2 services to run simultaneously to provide redundancy

**Comment by aalaesar** [comment]
hi.
Do we close this issue or is there any question ?

**Comment by quenenni** [comment]
No more question for me. I forgot to try your param last time, but I'll do it next time.
Anyway, now I know why, it's all good.
