### ISSUE TITLE
test on system space fails on a VPS

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#120]
The tests made in bin/systemChecks.sh return a
```
Error: /dev/root is not a valid filesystem
```
The line 
```
lo_fs=$(getFilesystem "$(dirname $lo_dir)") || exit 1
($lo_dir = /opt)
```
set the var to '/dev/root'

My df -h
```
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
/dev/root           36G    729M   34G   3% /
devtmpfs           2,0G       0  2,0G   0% /dev
tmpfs              2,0G       0  2,0G   0% /dev/shm
tmpfs              2,0G     14M  2,0G   1% /run
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              2,0G       0  2,0G   0% /sys/fs/cgroup
/dev/sda1          487M     25M  433M   6% /boot
```

I just removed the test from the script (I know I have enough space) and it's running ok atm.

**Comment by aalaesar** [comment]
Hi,
Sry, I missed this one last week
The first tests are not about available space but about the file system type, become compilation doesn't work if using symlinks for /opt.
So your VPS may have a filesystem that may not be well managed by the  `checkAvailableSpace` function, the error message came not from this one. [here](https://github.com/husisusi/officeonlin-install.sh/blob/726c7824a83a55cb8ec688f7146450bbd127704e/lib/checksys.sh#L26).
So we must know more about your VPS and what's its setup
like what the file type of `/dev/root` ?

**Comment by quenenni** [comment]
Sorry for the late answer.
My vps is a classic vps from OVH
If you need me to run specific commands on my vps, I'm all ears.
