### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by OutbackMatt** [husisusi/officeonlin-install.sh#124]
Running for the first time on Ubuntu Server 16.04

I get a command prompt back after a few seconds, and the only log created is preparation log with contents

Verifying System Requirements:
Memory: OK (3942 MiB)

The same detail is shown on the console
I've tried installing from /tmp/ and from /opt/
Either way the install script is copied from github correctly, the log directories are created, and empty log files created each run, but nothing happens.

What should I try?

**Comment by aalaesar** [comment]
Hello
Seems the new filesystem test is worst than before  😢 
Sorry the inconvenient.
Could you tell me more about your system ?
Os type, version, partition table with file system type (`df -Th`)
Lastly, could you run the script with bash -x ? something like:
`sudo bash -x AnyPathToTheScript/officeonline-install.sh`
and copy us the result ?

Thanks 😄 

(note for me: related to last post in #122 )

**Comment by aalaesar** [comment]
never mind.
I found out what's the cause 😃

**Comment by OutbackMatt** [comment]
Thank you, it is installing and compiling now
