### ISSUE TITLE
Poco version variables not holding despite having CURL installed

### ISSUE THREAD

**Issue by OutbackMatt** [husisusi/officeonlin-install.sh#126]
I can get lo to install, but the poco version variables do not work, despite CURL being installed
Subsequent runs of the script get same result (unlike some of the other issues reported here)

Ubuntu 16.04 Server (no GUI)

(PS I need to create an /opt/ directory first too)
Thanks too for the script and very responsive action on issues being reported

**Comment by aalaesar** [comment]
Hi there. 

I'm having a hard time figuring how the script is failing, what's the actual error you're getting?
Can you elaborate how the script behave ?

You can check the result of 
`curl -s https://pocoproject.org/ | awk -F'The latest stable release is ' '{printf $2}' | grep -Eo '^[^ ]+.\w'`
to see if the server do have access to the poco website.
You can also add echoes of the failing variable(s) in various places of the main script to see if the variable is set in the first place or when it looses its value.

you can also run the script with bash -x to get more verbosity.
everything should be stored in the logfiles, created at each run

PS : you can change where the script download and build the sources by copying/modifying the configuration file `officeonline-install.cfg`
Regards,
Aal

**Comment by OutbackMatt** [comment]
Thanks for your response

I did have a dead config file that I had created trying to solve the issue that cause the variables to lose their value. I had just uncommented the poco lines without adding the version detail.

The issue of not downloading poco remains.



Checking 
curl -s https://pocoproject.org/ | awk -F'The latest stable release is ' '{printf $2}' | grep -Eo '^[^ ]+.\w'
gives 1.7.9p3 as expected.

By adding  this under the comments, before the if line, to   ./bin/pocoPrep.sh

echo "*************************************"
echo "Poco Verison is:-" $poco_version
echo "Poco Dir is:-" $poco_dir
echo "Poco Verison Folder is:-" $poco_version_folder
echo "*************************************"

I get a poco-compilation.log that reads 

*************************************
Poco Verison is:- 1.7.9p3
Poco Dir is:- /opt/poco-1.7.9p3-all
Poco Verison Folder is:- 1.7.9
*************************************
--2017-09-12 11:49:52--  https://pocoproject.org/releases/poco-1.7.9/poco-1.7.9p3-all.tar.gz
Resolving pocoproject.org (pocoproject.org)... 162.209.7.4
Connecting to pocoproject.org (pocoproject.org)|162.209.7.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-12 11:49:53 ERROR 404: Not Found.



That URL created looks to match the poco website URL for downloading that tar.gz file

**Comment by aalaesar** [comment]
Just checking
seems POCO just released a new 1.7.9 version 
yesterday I got 1.7.**8**p3 
today 1.7.**9** (without the p3)
which is coherent with getting a 404 for this generated URL.
I'm running a test right now but a feel like it _**could be**_ a typo during the release of 1.7.9.
Can you retry now ?

There's also the possibility  the server is behind a corporate proxy that block some downloads. (But for this one I'm just guessing)

Regards
Aal.

**Comment by OutbackMatt** [comment]
You may be right about the new release having an impact

It seems to work today, without any changes from my end.
I first got that 404 Not Found with 1.7.8p3, and continued to get it yesterday with the 1.7.9p3, but today without the p3 on the end it seems to work.

Perhaps the script had an issue with the p3 in the version number??

**Comment by aalaesar** [comment]
Hi.
My test went ok (with no changes)
So I suppose  the root cause is bad timing beetween  using the script  and the new pico release.
The p3 is not hard coded so the script should not have any problem with  poco versions... Unless the poco  website is not coherent itself.
But I'll test this for good measures.
I have few questions : when the poco step fails, did the script stopped  or continued (tried) to build poco/ loolwsd  ?
If it stopped, I think this issue can be closed, unless  you have a recommendation about guessing poco current  version to avoid  this issue later. ☺️
Regards, Aal

**Comment by OutbackMatt** [comment]
Yes, previously the script stopped when it couldn't find the poco source

Today it installed fine (apparently) and I got a message at the end about a user name and password that I wrote down.

Now, how do I use it?
I have a loolwsd.service that is running (Ubuntu Server 16.04 - no GUI).
I have apache2, MySQL, Nextcloud, PHP7
In Nextcloud I have enabled the Collobora Online app, and the app is asking for a Collobora online server by 'URL (and port) of the Collabora Online server that provides the editing functionality as a WOPI client.'

DO I need to somehow make this service available as a webservice? Where/how do I do that?

**Comment by aalaesar** [comment]
Assuming you have a proper NAT/PAT/FireWall configuration. (i can't help on this one)
Following nextcloud's guide to install collabora works fine when you substitute the docker container by your new server (starting from step 2)
https://nextcloud.com/collaboraonline/
depending on your setup, you may have to change the reverse proxy configuration to point out your Loolwsd server's IP instead of localhost/127.0.0.1 in the guide
Regards, 
Aal

**Comment by OutbackMatt** [comment]
Thanks Aal.

I finally have this working.
Because I use LetsEncrypt certificates, I did have to change localhost to office.example.com in a couple of places. They are 
/opt/online/loolwsd.xml

and in the apache2 config file created at step 2 of the link that you provided

The real trick for me was restarting the loolwsd.service during testing, not just the apache2 service.

Again thanks for your help - awesome script.

**Comment by aalaesar** [comment]
I'm glad you made it work 😄 
Thank You and have fun! 👍
