### ISSUE TITLE
collabora code 2.1.4

### ISSUE THREAD

**Issue by ghost** [husisusi/officeonlin-install.sh#129]
Hello Devs.

Thanks for the script. Just executed it successfully. According to the help dialog 2.1.2 is installed now. Is there a way to install 2.1.4?

thanks and cheers

**Comment by Kassiematis** [comment]
It is possible to install 2.1.4. Change officeonline-install.cfg

`#set_online_regex='collabora-online'`

to

`set_online_regex='collabora-online-2-1'`

For some reason i get an error starting loolwsd. Copying the old loolwsd.xml over the new one fixes that. (don't forget to make a copy)

**Comment by Kassiematis** [comment]
Version 2.1.4-3 works like a charm, error has been fixed.

**Comment by ghost** [comment]
Ack. Thanks.

**Comment by edmonaft** [comment]
Hi,

I ran the script and installed it properly. So far, the only issue i am getting is that when i create a file (or upload), i cannot edit it.

It just briefly says "Connecting" then nothing happens.
