### ISSUE TITLE
system 'root' user has become 'lool' using sudo privilages

### ISSUE THREAD

**Issue by mercury64** [husisusi/officeonlin-install.sh#13]
After running this script, the file '/etc/group' has changed.
The following:
```
root:x:0:
sudo:x:27:root
```
became:
```
root:x:0:
sudo:x:27:lool
```
This caused me and my system a bit of grief.
I manually changed back to make my system happy again.

**Comment by Ark74** [comment]
>  I manually changed back to make my system happy again.

How did you?

**Comment by husisusi** [comment]
@mercury64 what are you talking about???
Yes, lool is in sudo group what is your problem?

**Comment by mercury64** [comment]
The specific problem is that user 'lool' was not correctly added to the 
sudoers group.

This becomes apparent when a regular user executes 'sudo', the sudo user 
becomes 'lool'.
As simple as mounting a drive from the desktop, usually asks for 
'Administrator' password, but after executing your script, and mounting 
a drive from the desktop, access is asking for 'lool' password.

After investigating, your script has changed the /etc/group file, and 
replaced sudo group user root with lool for the system. If anything, 
lool should be added or appended, NOT to replace root.

**Comment by Ark74** [comment]
> If anything, lool should be added or appended, NOT to replace root.

And you achieve it by doing....?

**Comment by husisusi** [comment]
I assume you are using Debian.
First, our script dose not touch your group file and did not change anything in this file.
Secondly,  to have a root in sudors group is not brilliant idea (nicely said), and your system (not our script) corrected this after the script add lool user in sudo group (line 46).
The sense of sudo to not use root password.

Best regards 

PS: The same thing makes Debian installation if you do not enter a root password
