### ISSUE TITLE
This is not a issue.

### ISSUE THREAD

**Issue by karthikjoe** [husisusi/officeonlin-install.sh#132]
Hi Expert's

I am not tech geek but still i am trying to learn. So i have installed own cloud on google VPS and we are recruiting consultancy so we mostly use office documents with collaborative editing.
Is this libreoffice online use for our purpose.
If you don't mind plsease help me to install this online office on my VPS by step by step.
Thanks in advance.

**Comment by husisusi** [comment]
RTFM
https://github.com/husisusi/officeonlin-install.sh/blob/master/README.md
