### ISSUE TITLE
loolwsd.service problem

### ISSUE THREAD

**Issue by Klippenhopper** [husisusi/officeonlin-install.sh#136]
Hello!

I´ve done a mistake,.
I deleted my loolwsd.service file
now it failed to start, and i dont get the right config.

`systemctl status loolwsd.service`

> loolwsd.service - LibreOffice Online WebSocket Daemon
   Loaded: loaded (/etc/systemd/system/loolwsd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2017-11-14 08:42:57 CET; 1s ago
  Process: 1214 ExecStart=/usr/bin/loolwsd --o:sys_template_path=/opt/lool/systemplate --o:lo_template_path=/opt/collaboraoffice
 Main PID: 1214 (code=exited, status=203/EXEC)
      CPU: 2ms

> Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Main process exited, code=exited, status=203/EXEC
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Unit entered failed state.
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Failed with result 'exit-code'.
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Service hold-off time over, scheduling restart.
Nov 14 08:42:57 ncvcollaborat systemd[1]: Stopped LibreOffice Online WebSocket Daemon.
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Start request repeated too quickly.
Nov 14 08:42:57 ncvcollaborat systemd[1]: Failed to start LibreOffice Online WebSocket Daemon.
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Unit entered failed state.
Nov 14 08:42:57 ncvcollaborat systemd[1]: loolwsd.service: Failed with result 'exit-code'.

 

 

`nano /etc/systemd/system/loolwsd.service` 

> [Unit]
Description=LibreOffice Online WebSocket Daemon
After=network.target

> [Service]
User=lool
ExecStart=/usr/bin/loolwsd --o:sys_template_path=/opt/lool/systemplate --o:lo_template_path=/opt/collaboraoffice5.1 --o:child_r$
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure

> [Install]
WantedBy=multi-user.target

**Comment by aalaesar** [comment]
Hi,
Did you used the script in the first place ?
You should be able to fix it by
Deleting the service file and then  running the script again with the exact same set of configuration / parameters with option  `-f lool` to force loolwsd compilation and installation.
Regards,
Aal.

**Comment by Klippenhopper** [comment]
ok 
I will delete loolwsd.service an start the script again.

**Comment by Klippenhopper** [comment]
> lool:x:1002:1002::/home/lool:
Von https://github.com/LibreOffice/core
   4de9091c6235..15fb717539c0  master     -> origin/master
Selected Tag: cp-5.3-30 2342ab8
Selected Tag: 2.1.2-14, origin/distro/collabora/collabora-online-cd ebedb6f
Loolwsd is already in the expected state and I'm not forced to rebuild.
Leaving here...

**Comment by aalaesar** [comment]
Yep.
That's why you need to force the look build with the `-f` option :wink:

**Comment by Klippenhopper** [comment]
Now I understand ! :100:

**Comment by Klippenhopper** [comment]
Now its a new error:

> make[2]: Verzeichnis „/opt/online“ wird betreten
  CXX      wsd/LOOLWSD.o
  CXX      wsd/ClientSession.o
In file included from wsd/LOOLWSD.cpp:106:0:
./common/UnitHTTP.hpp:86:18: error: ‘virtual bool UnitHTTPServerRequest::expectContinue() const’ marked ‘override’, but does not override
     virtual bool expectContinue() const override

> make[2]: *** [wsd/LOOLWSD.o] Fehler 1
Makefile:1167: die Regel für Ziel „wsd/LOOLWSD.o“ scheiterte
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet...
make[2]: Verzeichnis „/opt/online“ wird verlassen
Makefile:1703: die Regel für Ziel „all-recursive“ scheiterte
make[1]: *** [all-recursive] Fehler 1
make[1]: Verzeichnis „/opt/online“ wird verlassen
make: *** [all] Fehler 2
Makefile:736: die Regel für Ziel „all“ scheiterte
make: Verzeichnis „/opt/online“ wird verlassen

**Comment by aalaesar** [comment]
Erf :confused:
See #135 for the fix

**Comment by aalaesar** [comment]
hI @Klippenhopper 
can we close this issue ?
