### ISSUE TITLE
Error with installing using this script

### ISSUE THREAD

**Issue by ExaconAT** [husisusi/officeonlin-install.sh#138]
Ubuntu: 16.04 LTS
Nextcloud 12.0.3
Apache2
MariaDB
ALL ACTUAL

In file included from common/UnitHTTP.cpp:13:0:
common/UnitHTTP.hpp:86:18: error: ‘virtual bool UnitHTTPServerRequest::expectContinue() const’ marked ‘override’, but does not override
     virtual bool expectContinue() const override
                  ^
common/UnitHTTP.cpp: In constructor ‘UnitWebSocket::UnitWebSocket(const string&)’:
common/UnitHTTP.cpp:26:31: error: cannot declare variable ‘request’ to be of abstract type ‘UnitHTTPServerRequest’
         UnitHTTPServerRequest request(response, docURL);
                               ^
In file included from common/UnitHTTP.cpp:13:0:
common/UnitHTTP.hpp:64:7: note:   because the following virtual functions are pure within ‘UnitHTTPServerRequest’:
 class UnitHTTPServerRequest : public Poco::Net::HTTPServerRequest
       ^
In file included from common/UnitHTTP.hpp:18:0,
                 from common/UnitHTTP.cpp:13:
/usr/local/include/Poco/Net/HTTPServerRequest.h:69:15: note:    virtual bool Poco::Net::HTTPServerRequest::secure() const
  virtual bool secure() const = 0;
               ^
Makefile:1167: die Regel für Ziel „common/UnitHTTP.o“ scheiterte
make[2]: *** [common/UnitHTTP.o] Fehler 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
make[2]: Verzeichnis „/opt/online“ wird verlassen
Makefile:1703: die Regel für Ziel „all-recursive“ scheiterte
make[1]: *** [all-recursive] Fehler 1
make[1]: Verzeichnis „/opt/online“ wird verlassen
Makefile:736: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
make: Verzeichnis „/opt/online“ wird verlassen

**Comment by benreh** [comment]
Same problem on Debian 8 with g++ 4.9.2

**Comment by aalaesar** [comment]
Hi
This issue is a duplicate 
Please look here: #135
Regards
