### ISSUE TITLE
doen't install 

### ISSUE THREAD

**Issue by mrPsycho** [husisusi/officeonlin-install.sh#14]
here is log:
`checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking dependency style of g++... gcc3
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for setcap... /sbin/setcap
checking whether to run tests against a LibreOffice...`

here is what i see in the end:
blue screen with admin password 
error with `make`

**Comment by husisusi** [comment]
Why do you think it's a script bug?
Please let me know this output:
df -lah
free -m

**Comment by mrPsycho** [comment]
> root@zentyal:/tmp/officeonlin-install.sh# df -lah
> Filesystem                    Size  Used Avail Use% Mounted on
> sysfs                            0     0     0    - /sys
> proc                             0     0     0    - /proc
> udev                          2,8G     0  2,8G   0% /dev
> devpts                           0     0     0    - /dev/pts
> tmpfs                         577M   65M  512M  12% /run
> /dev/mapper/zentyal--vg-root  451G   67G  362G  16% /
> securityfs                       0     0     0    - /sys/kernel/security
> tmpfs                         2,9G   20M  2,8G   1% /dev/shm
> tmpfs                          50M     0   50M   0% /run/lock
> tmpfs                         2,9G     0  2,9G   0% /sys/fs/cgroup
> cgroup                           0     0     0    - /sys/fs/cgroup/systemd
> pstore                           0     0     0    - /sys/fs/pstore
> cgroup                           0     0     0    - /sys/fs/cgroup/cpu,cpuacct
> cgroup                           0     0     0    - /sys/fs/cgroup/perf_event
> cgroup                           0     0     0    - /sys/fs/cgroup/hugetlb
> cgroup                           0     0     0    - /sys/fs/cgroup/freezer
> cgroup                           0     0     0    - /sys/fs/cgroup/cpuset
> cgroup                           0     0     0    - /sys/fs/cgroup/devices
> cgroup                           0     0     0    - /sys/fs/cgroup/pids
> cgroup                           0     0     0    - /sys/fs/cgroup/net_cls,net_prio
> cgroup                           0     0     0    - /sys/fs/cgroup/memory
> cgroup                           0     0     0    - /sys/fs/cgroup/blkio
> systemd-1                        -     -     -    - /proc/sys/fs/binfmt_misc
> hugetlbfs                        0     0     0    - /dev/hugepages
> mqueue                           0     0     0    - /dev/mqueue
> debugfs                          0     0     0    - /sys/kernel/debug
> tracefs                          0     0     0    - /sys/kernel/debug/tracing
> fusectl                          0     0     0    - /sys/fs/fuse/connections
> /dev/md127                    917G  614G  257G  71% /massive
> /dev/md0                      236M  107M  117M  48% /boot
> cgmfs                         100K     0  100K   0% /run/cgmanager/fs
> udev                          2,8G     0  2,8G   0% /proc/bus
> tmpfs                         577M  4,0K  577M   1% /run/user/1000
> /dev/mapper/other             219G  134G   74G  65% /massive/shares/other
> /dev/sde1                     458G  371G   64G  86% /mnt/disk1
> binfmt_misc                      0     0     0    - /proc/sys/fs/binfmt_misc
> root@zentyal:/tmp/officeonlin-install.sh# free -m
>               total        used        free      shared  buff/cache   available
> Mem:           5766        1613         771          98        3381        3701
> Swap:          8191         362        7829

**Comment by husisusi** [comment]
I love zentyal too, but zentyal is not Ubutu. Zentyal is based on Ubuntu but has own repository.
We can not support all Ubuntu|Debian based  OS.
**"Script to install Office Online on Ubuntu 16.04 and Debian 8.7"**

**Comment by mrPsycho** [comment]
but why i see this: 
make: *** No rule to make target 'run'.  Stop.
?

**Comment by husisusi** [comment]
Because your LibreOffice not built.
