### ISSUE TITLE
[Help] - Failing to get a working websocket from collabora online3.0

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#144]
Hi there
I'm looking for experience returns of  making a working loowsd using the **collabora online 3.0** branch.

by setting
`set_online_regex='collabora-online-[0-9]'`
the set feature work properly to get the latest branch
```
Searching for a set named collabora...
Core branch: distro/collabora/cp-5.3
Online branch: distro/collabora/collabora-online-3-0
```
instead of `distro/collabora/collabora-online-cp`.

The script finish properly but the websocket daemon is unable to provide any content:

By using the latest richdocument app on nextcloud,
the app can't display the document (the toolbar and cursor appears but not the doc itself), and sometime I have socket failures with a bunch of non human-friendly errors.
**This is the main reason I haven't push any modification on the default set_online_regex yet**

I'm aware this could be a failure caused by any element in the app chain: 
 - the richdocument app
 - the reverse proxy 
 - the websocket.
 - This script (build options, set of branches)
 - The code. (bugs)

As I understand, some users have changed their config to use this branch.
I requires their help:
If you got it working, can you tell me more about your environments, tests, failures and success ?
thanks.
Best regards
Aal.

**Comment by quenenni** [comment]
As I didn't succeed to compile with the last v2, let me help you by trying the v3.

But my question is, knowing there is a problem with libreoffice core, the commit I pointed in the other ticket, and the fact that there are a shit ton of newer commits after that one that can't be actif when compiling, shouldn't it be better to wait for at least this bug to be corrected.

If not, it means we are trying to compile the top notch lool with a quite old libreoffice core.
Maybe that's the problem?

I'm going to give a try and will let you know the sresult.

**Comment by quenenni** [comment]
Another question.

Do you think poco 1.7.9 is ok with online v3 or are we supposed to use poco 1.8 with it?

**Comment by quenenni** [comment]
Well.. Good news, my first attempt is successful.

Here is what I can see when going in the Help -> About menu.
```
This version of LibreOffice Online is powered by

LOOLWSD
3.0.0 (git hash: 6a3d30fa)

LOKit
Collabora OfficeDev 5.3-32 (git hash: 07ff6ea)
```

Here are the parameters I used.

* For libreoffice:
I added a line to make a pause just before starting to compile it.
In officeonline-install.sh, juste before the line
`source "$ScriptFullPath/bin/coreBuild.sh"`
I added this:
`read -n1 -rsp $"push any key to continue"`
.
So when I see thi msg, in another screen, I go in the libreoffice dir and do this command:
`git checkout 07ff6eaaba5a7ecd0e9e04507190df779ac5cfe4`

* For Poco:
I chose the v1.7.9p2.
In lib/default.cfg
```
poco_version_latest="1.7.9p2"
poco_version_folder="1.7.9"
```

* For Online:
In officeonline-install.cfg
```
set_online_regex='collabora-online-[0-9]'
```

**Comment by aalaesar** [comment]
Hi @quenenni 
congrats 👍 
can you tell me:
- If you can open and edit correctly docs with it ?
- Whats you setup ? (OS, nexcloud ? richdocument apps ?)

(edited : saw your other post about the commit id and the lo_src_commit not working after posting)

**Comment by quenenni** [comment]
Thank you. 

It took me a while figuring out what commit was the cause. Lot of trials & errors compiling libreoffice.  Lucky me, the crash happened only after one hour compiling.. It could have been after 10 hours (my lool server is a small vps so the total number of hours to compile of big.. but still, I'm very happy with the speed it deserves the docs) 

>     If you can open and edit correctly docs with it ?

I tested several files on several nextcloud servers and all worked. Open -> change stuff -> check the new menus (nice!) -> close -> re-open (only spreadsheet and documents though, no presentation files)

> Whats you setup ? (OS, nexcloud ? richdocument apps ?)

Our Nextcloud servers:
Debian Jessie & Stretch
Nextcloud 12.0.3 
Nginx version: nginx/1.10.3 & Apache v2.4.25-3+deb9u3
Richdocuments: 1.12.34

**Comment by aalaesar** [comment]
Finally !! got it working with this parameters !

``` bash
set_online_regex='collabora-online-[0-9]'
lo_src_tag='cp-5.3-33' 
poco_version=1.7.9p2
```
Thank you for the support @quenenni  !
I'll check if changing poco version may create issue on the final result

Regards, Aal

**Comment by aalaesar** [comment]
no issue with latest poco available (1.8.0.1)
closing

**Comment by quenenni** [comment]
Nicely done.

I guess see you for the next bug :)

**Comment by Ark74** [comment]
> set_online_regex='collabora-online-[0-9]'
> the set feature work properly to get the latest branch
> 
> Searching for a set named collabora...
> Core branch: distro/collabora/cp-5.3
> Online branch: distro/collabora/collabora-online-3-0
> 
> instead of distro/collabora/collabora-online-cp.

As for the time of writting, i believe it's better to use,
`set_online_regex='collabora/collabora-online-3$'`

otherwise we end with some weird branches that were created through the passing of time.
