### ISSUE TITLE
How to use self-signed certificate

### ISSUE THREAD

**Issue by Patriot2407** [husisusi/officeonlin-install.sh#145]
This is not an issue for this script at all, but everyone here seems to be very knowledgeable about LibreOffice Online, and I was wondering if anyone knows how to set Collabora to use self-signed certificate for my test machine? Eventually when it is in production, it will use a legitimate SSL certificate, but for demo purposes, I want this to be a LAN-only demo. Yes I know about Let's Encrypt, but I'd like to use my own private certificate for testing.

**Comment by Patriot2407** [comment]
It seems like it may be a Curl issue. I think that if I can set curl to check my local CA, then it could solve my issue.

**Comment by aalaesar** [comment]
Sorry can't help you here
I usually use a reverse proxy to setup front end encryption for multiple services so I don't spend to much time managing multiple certs.

> It seems like it may be a Curl issue. I think that if I can set curl to check my local CA, then it could solve my issue.

I'm not sure I understand your issue here. can you elaborate ?

**Comment by Patriot2407** [comment]
Curl has a security feature that makes it check internet CAs to check validity of SSL certificate. Therefore, it will not verify a self-signed certificate on my LAN.

**Comment by ibeardslee** [comment]
`curl -k`  to use 'insecure mode' to ignore the verification of your self-signed certificates.

But to get things working with snakeoil or self signed certificates, you can to copy the certificates between the libreoffice online server and your document server (nextcloud/seafile etc).  With Ubuntu copy the server's certificate to _/etc/ssl/certs/otherserver.crt_ on each server and run `update-ca-certificates`

**Comment by Patriot2407** [comment]
This is what I get in my log files
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by Patriot2407** [comment]
@ibeardslee Are you saying I need to put my CA certificate in the document servers /etc/ssl/certs/ in order to add it as a trusted CA?

**Comment by Patriot2407** [comment]
I added my CA to system store and it did nothing.

**Comment by Patriot2407** [comment]
Looks like cURL has it's own certificate store.

**Comment by Patriot2407** [comment]
My NextCloud server and document server are on the same machine BTW.

**Comment by Patriot2407** [comment]
I got this off of https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list

Which fixed cURL. I was able to cURL the domain name without error, however cURL is still throwing errors in docserver.



"The simple answer to this is that pretty much each application will handle it differently.

Also OpenSSL and GNUTLS (the most widely used certificate processing libraries used to handle signed certificates) behave differently in their treatment of certs which also complicates the issue. Also operating systems utilize different mechanisms to utilize "root CA" used by most websites.

That aside, giving Debian as an example. Install the ca-certificates package:

apt-get install ca-certificates
You then copy the public half of your untrusted CA certificate (the one you use to sign your CSR) into the CA certificate directory (as root):

cp cacert.pem /usr/share/ca-certificates
And get it to rebuild the directory with your certificate included, run as root:

dpkg-reconfigure ca-certificates
and select the ask option, scroll to your certificate, mark it for inclusion and select ok."

**Comment by ibeardslee** [comment]
When I was using the self-signed certificates on my initial test set up, I had to put the certificates used by the NextCloud Apache2 onto my Libreffice Online server, and the certificates used by my LibreOffice Online Apache2 onto my NextCloud server. Both went into /etc/ssl/certs/ and update-ca-certificates was run.

Hmm, don't know the implications of having NextCloud and LibreOffice Online server (docker or 'native'?) on the same machine as far as certificates go, it's not something I have tried yet.

**Comment by Patriot2407** [comment]
It works fine when I put our actual domain SSL certificate on it, just not when we put a self-signed one.

**Comment by Patriot2407** [comment]
Docker has never been installed on this machine. I compiled using this script.

**Comment by Kassiematis** [comment]
Try this

cat ca-chain.cert.pem >> /var/www/owncloud/resources/config/ca-bundle.crt

**Comment by Patriot2407** [comment]
I just tried that. Still didn't help.

**Comment by Kassiematis** [comment]
Mayby this issue can help. #61

**Comment by Patriot2407** [comment]
@Kassiematis Interesting. When I go to https://office.MYDOMAIN.com:9980/ i get this cert appearing onlineoffice-install.com. Any idea why that would be?

**Comment by Patriot2407** [comment]
Thank you, your reference to https://github.com/husisusi/officeonlin-install.sh/issues/61 fixed my isse. Specifically where I had to cat my self-signed certs and ca cert into loolwsd, and then cat it into nextcloud. Thank you very much!!

**Comment by Patriot2407** [comment]
So this is proof that it is possible to run office online along with NextCloud on same machine, with self-signed SSL certificate with private Certificate Authority. Thanks all for the help!

**Comment by Ark74** [comment]
I'm curious of this, if the communication between NC and LibOO is locked to them only it should.
But once you bring the user browser into account it will complain, at least on the first run.

I've played a lot with ssl, and to be honest it makes things more complicated but not really sure how much secure. I'm looking at you NSA.

**Comment by Patriot2407** [comment]
If you have a proper private CA, and setup your SSL certificates properly (deploy via GPO on windows), then the user's browser/the user themselves should never get a warning. Even on first run. And since you have 100% control over what TLS encryption and ciphers you can use, since you are your own CA, you can make it as secure as TLS will allow. You can also instantly upgrade and revoke old TLS encryption suites as they become (more) vulnerable. This is one major reason I like to be my own CA on my LAN. I have complete control over security. Which is also why I immediately liked LibreOffice online. Best thing since sliced bread, and I can control security and every aspect at a granular level if I wish. Once I have everything 100% figured out, which these amazing people here on this repo are helping me to achieve.

**Comment by Patriot2407** [comment]
I have even written a piece of javascript to allow Firefox to use my self-signed certificates, granted you have to open, then close, and reopen firefox for the new certificates to get loaded into it's store.
