### ISSUE TITLE
Document tiles not loading

### ISSUE THREAD

**Issue by Patriot2407** [husisusi/officeonlin-install.sh#148]
I have an interesting issue, where compile is successful, and I can load document, but tile does not load. I cannot type. No error is thrown in NextCloud, only in systemctl status. output below:

loolwsd.service - LibreOffice OnLine WebSocket Daemon
   Loaded: loaded (/etc/systemd/system/loolwsd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-12-19 01:54:31 EST; 3min 31s ago
  Process: 2378 ExecStartPre=/bin/chown lool: /usr/local/var/cache/loolwsd (code=exited, status=0/SUCCESS)
  Process: 2373 ExecStartPre=/bin/mkdir -p /usr/local/var/cache/loolwsd (code=exited, status=0/SUCCESS)
 Main PID: 2384 (loolwsd)
    Tasks: 10
   Memory: 107.9M
      CPU: 2.954s
   CGroup: /system.slice/loolwsd.service
           â”œâ”€2384 /opt/online/loolwsd --o:sys_template_path=/opt/online/systemplate --o:lo_template_path=/opt/libreoffice/instdir --o:child_root_path=/opt/online/jails --o:admin_console.username=admin --o:admin_console.password=*******
           â”œâ”€2388 /opt/online/loolforkit --losubpath=lo --systemplate=/opt/online/systemplate --lotemplate=/opt/libreoffice/instdir --childroot=/opt/online/jails/ --clientport=9980 --masterport=9981 --rlimits=limit_virt_mem_mb:0;limit_stack_mem_kb:8000;limit_file_size_mb:0;limit_num_open_files:0
           â””â”€2400 /opt/online/loolforkit --losubpath=lo --systemplate=/opt/online/systemplate --lotemplate=/opt/libreoffice/instdir --childroot=/opt/online/jails/ --clientport=9980 --masterport=9981 --rlimits=limit_virt_mem_mb:0;limit_stack_mem_kb:8000;limit_file_size_mb:0;limit_num_open_files:0

Dec 19 01:54:40 Media loolwsd[2384]: kit-02390-02403 06:54:40.509124 [ lokit_001 ] ERR  Tile rendering requested without views.| kit/Kit.cpp:892
Dec 19 01:54:44 Media loolwsd[2384]: wsd-02384-02399 06:54:44.888145 [ docbroker_001 ] ERR  Socket #22 SSL BIO error: error:140D00CF:SSL routines:SSL_write:protocol is shutdown (errno: Success)| ./net/SslSocket.hpp:273
Dec 19 01:54:44 Media loolwsd[2384]: wsd-02384-02399 06:54:44.888570 [ docbroker_001 ] WRN  ToClient-0004: Exception while closing socket for docKey [/index.php/apps/richdocuments/wopi/files/146_oc54p1f7p71a]: error:140D00CF:SSL routines:SSL_write:protocol is shutdown| wsd/ClientSession.cpp:919
Dec 19 01:54:44 Media loolwsd[2384]: kit-02390-02403 06:54:44.891414 [ lokit_001 ] ERR  No socket associated with WebSocketHandler 0x0x57e2130| ./net/WebSocketHandler.hpp:100
Dec 19 01:54:45 Media loolwsd[2384]: wsd-02384-02399 06:54:45.399378 [ docbroker_001 ] ERR  #18: Wrote outgoing data -1 bytes. (errno: Broken pipe)| ./net/Socket.hpp:927
Dec 19 01:54:45 Media loolwsd[2384]: wsd-02384-02399 06:54:45.400264 [ docbroker_001 ] ERR  #18: Wrote outgoing data -1 bytes. (errno: Broken pipe)| ./net/Socket.hpp:927
Dec 19 01:54:53 Media loolwsd[2384]: wsd-02384-02387 06:54:53.931301 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: true, finished: true| ./net/Socket.hpp:507
Dec 19 01:54:53 Media loolwsd[2384]: wsd-02384-02387 06:54:53.932460 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: true, finished: true| ./net/Socket.hpp:507
Dec 19 01:54:53 Media loolwsd[2384]: wsd-02384-02387 06:54:53.932588 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: false, finished: true| ./net/Socket.hpp:507
Dec 19 01:54:53 Media loolwsd[2384]: wsd-02384-02387 06:54:53.932619 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_001], started: false, finished: true| ./net/Socket.hpp:507

**Comment by Kassiematis** [comment]
I found this on internet.

https://help.nextcloud.com/t/collobora-and-nextcloud-12-wopi-checkfileinfo-failed-with-404-not-found/19700

**Comment by Patriot2407** [comment]
This is my nextcloud conf:
<VirtualHost *:443>
ServerName office.DOMAIN.lan:443

# SSL configuration, you may want to take the easy route instead and use Lets Encrypt!
SSLEngine on
SSLCertificateFile /etc/ssl/private/office.cer
SSLCertificateKeyFile /etc/ssl/private/office.key
SSLProtocol             all -SSLv2 -SSLv3
SSLCipherSuite ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
SSLHonorCipherOrder     on

# Encoded slashes need to be allowed
AllowEncodedSlashes NoDecode

# Container uses a unique non-signed certificate
SSLProxyEngine On
SSLProxyVerify None
SSLProxyCheckPeerCN Off
SSLProxyCheckPeerName Off

# keep the host
ProxyPreserveHost On

# static html, js, images, etc. served from loolwsd
# loleaflet is the client part of LibreOffice Online
ProxyPass           /loleaflet https://127.0.0.1:9980/loleaflet retry=0
ProxyPassReverse    /loleaflet https://127.0.0.1:9980/loleaflet

# WOPI discovery URL
ProxyPass           /hosting/discovery https://127.0.0.1:9980/hosting/discovery retry=0
ProxyPassReverse    /hosting/discovery https://127.0.0.1:9980/hosting/discovery

# Main websocket
ProxyPassMatch "/lool/(.*)/ws$" wss://127.0.0.1:9980/lool/$1/ws nocanon

# Admin Console websocket
ProxyPass   /lool/adminws wss://127.0.0.1:9980/lool/adminws

# Download as, Fullscreen presentation and Image upload operations
ProxyPass           /lool https://127.0.0.1:9980/lool
ProxyPassReverse    /lool https://127.0.0.1:9980/lool
</VirtualHost>

**Comment by aalaesar** [comment]
S###t this one again.
That's an issue I had for a while when testing building from collabora 3.0. ( #144 )
I'm thinking it's an integration incompatibility with lokit and loolwsd. 
Did disappeared though when I fixed the search git commit function so I supposed it was the bad checkout command that was causing bad integration issue
Did you rebuilt libre office after the new script update ?
Did you specified a tag when building libre office  ?
Regards Aal.

**Comment by Kassiematis** [comment]
In the file resources/config/ca-bundle.crt did you import the public self-signed cert? only the ca-certs should be imported.

**Comment by Patriot2407** [comment]
@aalaesar Alright I will try that.

@Kassiematis I was using a self-signed certificate.

**Comment by Patriot2407** [comment]
And @aalaesar I ran this compile with the newest update to the script about 8 hours ago.

**Comment by Patriot2407** [comment]
I will comment my progress later. Seems LO fails to build on latest commit. i will switch it up in a little bit and report progress on this issue when I finish next compile.

**Comment by aalaesar** [comment]
@czebiniak 
for LO:
tag cp-5.3-35 introduced a unit test failure that has been fixed later
tag cp-5.3-36 has just been released yesterday  I have'nt tested it yet
seems there have been a lot of changes before the 36

**Comment by Patriot2407** [comment]
Alright thanks, I am trying tag cp-5.3-35

**Comment by aalaesar** [comment]
This one is failing to build LO

**Comment by Patriot2407** [comment]
yes it is.

**Comment by czebiniak** [comment]
Is there anyway to see most recent commits on github website? Or do I have to use giot command in cli to see the latest commits? I am looking at https://github.com/LibreOffice/core/commits/distro/collabora/cp-5.3  ANd this does not show cp-5.3-35

**Comment by aalaesar** [comment]
Github always show latest state. And display the latest commit on top of the directory

**Comment by aalaesar** [comment]
@czebiniak 
SO did you get something working properly ?
I've got good results with `tag cp-5.3-33`

**Comment by Patriot2407** [comment]
I will try that. I have not yet gotten any recent builds to successfully compile.

**Comment by aalaesar** [comment]
Hi
Any news ?
Should work with the latest PR

**Comment by Ark74** [comment]
It does on fcdecb8d98e471f6232641b21e09efca4c58b05b
![loolws](https://user-images.githubusercontent.com/7444518/34390833-da02200e-eb07-11e7-9870-4b63ea5b62d0.png)

**Comment by aalaesar** [comment]
By the way,
**Any feedback on the script execution time ?**
I'm testing Jenkins CI on my lab and got a successful run in 'just' 2h30m, building from scratch.
Compared to previous tests done in early 2017 with similar setup(4h30m), this is much faster.

**Comment by Ark74** [comment]
Well, I suppose that it depends a lot if the equipment is dedicated or shared (VPS).

CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
Cores: 2
RAM: 8 GB

Timewatch.log

```
Started at 2017-12-22 07:35:38
Ended at 2017-12-22 16:48:48
```

**Comment by Patriot2407** [comment]
It works.
