### ISSUE TITLE
sed issue

### ISSUE THREAD

**Issue by Patriot2407** [husisusi/officeonlin-install.sh#149]
Does this seem okay? Get this every time I run the newly updated script. Also, it doesn't seem to be selecting libreoffice 6, or amI mistaken?

From https://github.com/LibreOffice/core
   43b5d6b..5aa5843  libreoffice-6-0 -> origin/libreoffice-6-0
   bdcbf60..9f3b61e  master     -> origin/master
Selected Tag: cp-5.3-36, origin/distro/collabora/cp-5.3 bb5e55d
sed: -e expression #1, char 32: unknown command: `u'
sed: -e expression #1, char 32: unknown command: `u'
sed: -e expression #1, char 32: unknown command: `u'
sed: -e expression #1, char 32: unknown command: `u'

**Comment by Patriot2407** [comment]
[log.txt](https://github.com/husisusi/officeonlin-install.sh/files/1572253/log.txt)

for readability

**Comment by Patriot2407** [comment]
Alright I solved the issue of switching to ver 6.0. I had to change my set. Apologies,I am still learning the structure of this.

**Comment by Patriot2407** [comment]
Anyway, the issue is not about LO ver 6, the issue is with the sed. Does anyone else get this weird sed output?

**Comment by aalaesar** [comment]
I understand  you have changed the set settings. What are  your settings ?

**Comment by Patriot2407** [comment]
I deleted the directory, and git cloned fresh install. I have not changed any configs in config file and I get the sed error. Please ignore the set comments above. I have reverted back to cp-5.3
I still get sed errors on fresh clone of the script.

**Comment by aalaesar** [comment]
Hi
just reproduced.
This is an issue with sed separators contained in a variable.
I'll push a fix soon

**Comment by Patriot2407** [comment]
Ok thanks.
