### ISSUE TITLE
LO Online build fails from master

### ISSUE THREAD

**Issue by ohmer1** [husisusi/officeonlin-install.sh#154]
LibreOffice Online is not currently buildable with the script. It crashes with this error:

```
/opt/libreoffice/cppcanvas/qa/extras/emfplus/emfplus.cxx:91:Test::testFdo77229
equality assertion failed
- Expected: 65024
- Actual  : 16777215

Test::testFdo77229 finished in: 671ms
emfplus.cxx:91:Assertion
Test name: Test::testFdo77229
equality assertion failed
- Expected: 65024
- Actual  : 16777215

Failures !!!
Run: 1   Failure total: 1   Failures: 1   Errors: 0
You need gdb in your path to show backtraces

Error: a unit test failed, please do one of:
make CppunitTest_cppcanvas_emfplus CPPUNITTRACE="gdb --args"
    # for interactive debugging on Linux
make CppunitTest_cppcanvas_emfplus VALGRIND=memcheck
    # for memory checking
make CppunitTest_cppcanvas_emfplus DEBUGCPPUNIT=TRUE
    # for exception catching

make[1]: *** [/opt/libreoffice/workdir/CppunitTest/cppcanvas_emfplus.test] Erreur 1
make[1]: *** Attente des tâches non terminées....
/opt/libreoffice/solenv/gbuild/CppunitTest.mk:101 : la recette pour la cible « /opt/libreoffice/workdir/CppunitTest/cppcanvas_emfplus.test » a échouée
Makefile:263 : la recette pour la cible « build » a échouée
make: *** [build] Erreur 2
```

I found someone commenting on the bug #140 that he was having the same issue. Like he suggested, defining a previous commit allow the script to complete the build with success.

**Comment by aalaesar** [comment]
Hi. it happens sometimes that a new tagged commit in the collabora branch is broken.
You still can specify an older tag to use in your config file or as a parameter in the cli.
This issue will be fixed eventually by the project and the team working on this branch.
 Regards, Aal.:relaxed:

**Comment by joergmschulz** [comment]
which would be a recommended tag? The version I compiled today failed to accept ssl connections; to be sure, I am currently rebuilding all and will report again.
see #155 / some tags seem to work
