### ISSUE TITLE
Does this work on 18.04?

### ISSUE THREAD

**Issue by schniepp** [husisusi/officeonlin-install.sh#159]
I am wondering if someone has tried to port this to 18.04. Would many changes have to be made? 
Any plans to release a 18.04 version in the near future?

**Comment by adamryczkowski** [comment]
Yes, it does. The only thing I needed to do, is to manually install the `npm` after the first (unsuccessful) script run.

Also remember, that testing the installation is a bit involved. The way I did:

1. Made sure that the server was accepting local documents by editing the local systemd script and adding `--o:storage.filesystem[@allow]=true`.
2. Uploaded some office files somewhere accessible by the `lool` user to the server.
3. Tested with https://192.168.0.1:9980/loleaflet/dist/loleaflet.html?file_path=file:///home/lool/file.xlsx&host=wss://localhost:9980

**Comment by Ark74** [comment]
> Yes, it does. 

Nice to know! :+1:

**Comment by aalaesar** [comment]
Hi. Nice to know.
Sry I don't have time right now to investigate.
So what happened to fail on the npm installation  ?

Also keep in mind that using storage.filesystem open a path traversal vulnerability.
Do not use it in production environment ! See #93.

**Comment by schniepp** [comment]
To all:
Thank you so much for getting back to my question!
Actually, I was able to get `lool` going on my 18.04 system by using the ubuntu packages that are now provided by Collabora: [https://www.collaboraoffice.com/code/#packages_for_linux_x86_64_platform](https://www.collaboraoffice.com/code/#packages_for_linux_x86_64_platform). This is very fast and did not need any compiling. I don't think I had to do a lot of other changes to get it going. I also set up the reverse proxy correctly as described on that page. This allows me to use it via SSL in my nextcloud system (running on the same server), which also uses SSL/https. However, I also tested it on another machine that simply uses http (without the reverse proxy), and it just works as well.

**Comment by Patriot2407** [comment]
@schniepp thanks for the info!

**Comment by Ark74** [comment]
@schniepp Correct me if i'm wrong but you might also install [CODE](https://www.collaboraoffice.com/code/) (Collabora requires a license) by using docker which is cleaner/backwards compatible for your system, right?

The main issue to compile is to have the LibreOffice Online with no limit to edit/review files.
If you have no issues with a 10/20 limit by CODE, then I guess APT/Docker are clearly easier alternatives.

Cheers!

**Comment by schniepp** [comment]
@Ark74 Thanks for pointing this out! I was not aware of the 10/20 limit... I was preferring the ubuntu packages over Docker, as I had read in a few places that the Docker images used up a lot of RAM. What are you referring to regarding backwards compatibility? I just thought that native packages were cleaner and more efficient on resources. 
If I run into the 10/20 limit too often, I will try to get it compiled.

**Comment by Ark74** [comment]
El 17 de junio de 2018 3:49:05 PM CDT, "Prof. Hannes C. Schniepp" <notifications@github.com> escribió:
>@Ark74 Thanks for pointing this out! I was not aware of the 10/20
>limit... I was preferring the ubuntu packages over Docker, as I had
>read in a few places that the Docker images used up a lot of RAM. 

Both docker and apt packages will use RAM, the first document will take around 150mb and the next ~50mb, so it doesn't matter which you use it will use RAM as the main resource.

>What
>are you referring to regarding backwards compatibility?

You can run docker I guess since 14.04 or earlier and it will be compatible to run CODE without issues.

> I just thought
>that native packages were cleaner and more efficient on resources. 

Maybe, but not by much.

>If I run into the 10/20 limit too often, I will try to get it compiled.

-- 
Luis

**Comment by titansmc** [comment]
i had do `sudo apt-get install npm ` and ` npm install -g npm ` as someone else mentioned already, only installing npm didn't work
