### ISSUE TITLE
Missing npm package in dependencies

### ISSUE THREAD

**Issue by emamona** [husisusi/officeonlin-install.sh#161]
Build fails on Nextcloud Tech and Me prebuild vm (16.04 OVA) , I had to apt install npm manually.
Re-run officeonlin-install.sh and then build goes on.

**Comment by ghost** [comment]
Same here on 18.04

**Comment by fishter** [comment]
On my Ubuntu 18.04 it actively removes npm and then fails with the message to install it.

**Comment by DaSimme** [comment]
> On my Ubuntu 18.04 it actively removes npm and then fails with the message to install it.

Same here. Any tips for a manual workaround?
I'm currently lost.

**Comment by Ark74** [comment]
It's quite straight forward:

> I had to apt install npm manually.
> Re-run officeonlin-install.sh and then build goes on.
