### ISSUE TITLE
POCO sources fetch error

### ISSUE THREAD

**Issue by pieroperuzzi** [husisusi/officeonlin-install.sh#163]
Hi , just try to run your script , but it fails when trying to fetch POCO sources ( because of https://pocoproject.org/ home page changed ).

Please change 

poco_version_latest=$(curl -s https://pocoproject.org/ | awk -F'The latest stable release is ' '{printf $2}' | grep -Eo '^[^ ]+.\w')

with 

poco_version_latest=$(echo$(curl -s https://pocoproject.org/ | awk -F'Latest Release:' '{printf $2}') | sed 's/\s.*$//')

in  lib/default.cfg

Piero

**Comment by joergmschulz** [comment]
Hi, @pieroperuzzi  do you think you can create a pull request on this change?

**Comment by ghost** [comment]
@joergmschulz it's done in the mentioned PR.

**Comment by Ark74** [comment]
@mathiasblc 
This has already been merged into master with https://github.com/husisusi/officeonlin-install.sh/pull/164

**Comment by aalaesar** [comment]
@husisusi 
I think this issue can be closed
