### ISSUE TITLE
unable to edit

### ISSUE THREAD

**Issue by masikmos** [husisusi/officeonlin-install.sh#167]
If page refresh after you push key

just install

For Ubuntu 16.04
`apt install hunspell-en-us libasyncns0  libepubgen-dev libreadline5  librecode-dev librecode0 librest-0.7-0 librevenge-0.0-0 librevenge-dev`

And for Ubuntu 18.04
`apt install hunspell-en-us libasyncns0 libemf1 libepubgen-0.1-1 libepubgen-dev libreadline5 libreadline7 librecode-dev librecode0 librest-0.7-0 librevenge-0.0-0 librevenge-dev`

Your Welcome

**Comment by aalaesar** [comment]
Hi @masikmos 
thank you for sharing.
I need some infos for updating the script:
- is it a build dependency  or a running dependency ? 
- for libreOffice-core or online ?
