### ISSUE TITLE
 Please update the script to the latest versions of distributions.

### ISSUE THREAD

**Issue by Stanislav1989** [husisusi/officeonlin-install.sh#168]
Hello A big request to update the scrit to current versions of distributions. Now the script requires a large number of changes. Problems with dependencies, using the example of the npm package and its dependencies, are very many problems. As I understand the script, judging by the content created on the Debian Jessie distribution. Sorry for my English.

**Comment by aalaesar** [comment]
Hi @Stanislav1989 
thank you for asking.
I  have lost some changes you are referring to.
Can you reference the ones you had in mind when you opened the issue ?
thank you! :smiley: 
Regards.
Aal.

**Comment by joergmschulz** [comment]
just compiled alright on buster. Only one change needed: bin/system:
if [ "${DIST}" = "Debian" ]; then
  if [ "${CODENAME}" = "_buster_" ];then
    ssl_fix_dirty

**Comment by joergmschulz** [comment]
the current version lacks npm as packet that has to be installed (just testing on a vanilla buster server)

**Comment by Gomez** [comment]
See https://github.com/husisusi/officeonlin-install.sh/issues/175#issuecomment-483522485
