### ISSUE TITLE
 How to add dictionaries?

### ISSUE THREAD

**Issue by Leocheine** [husisusi/officeonlin-install.sh#169]
How to add dictionaries?
Only the en-US dictionary has been added

**Comment by joergmschulz** [comment]
install hunspell-YourLanguage

**Comment by Ark74** [comment]
Install them by apt, libreoffice will pick them up.
https://github.com/husisusi/officeonlin-install.sh/blob/master/lib/default.cfg#L27

**Comment by Leocheine** [comment]
> install hunspell-YourLanguage


Thanks, this was the solution.

**Comment by joergmschulz** [comment]
would you mind closing this issue accordingly? Thank you!
