### ISSUE TITLE
Last good configuration known

### ISSUE THREAD

**Issue by adiluzio** [husisusi/officeonlin-install.sh#176]
####################
 set_online_regex='collabora/collabora-online-4$' #CODE 4 Branch
 lool_src_commit='173510fdbf6f52d1d6288b809c8d14bc630afd20' #CODE-4-RC2
 set_core_regex='cp-6.0$' #LibO 6.0.x
 #########

I tried this and it builds fine but loolwsd crashes randomly.
I also tried this configuration:

 ##########################
 set_core_regex='cp-5.3$'
 set_online_regex='collabora/collabora-online-3$'
 lo_src_branch='distro/collabora/cp-5.3'
 lo_src_tag='cp-5.3-61'
 lool_src_tag='3.4.2-1'
 ###########################

And it doesn't build anymore.
Is there anyone who can please tell me what is the latest good configuration nowadays?
Many thanks in advance.

**Comment by adiluzio** [comment]
Sorry for all the mess I made in writing the post. ^_^"""""

**Comment by tiredofit** [comment]
I don't use this script to install Libreoffice Online however it gave inspiration for building a Docker container as well as the long thread regarding working versions.
The above versions you have listed seem to be the last version that works for me at this time. Even cp-5.3-62 fails and LOOL 3.4.3-1.

Good luck!

**Comment by adiluzio** [comment]
Thanks for reply.
I'll write here if I'll find a stable combination of CORE and LOOL.

P.s. maybe I didn't understand correctly, did someone create libreoffice online docker containers that do not have the strict limitations of the collabora online docker (10 docs, 20 connections)?

**Comment by Ark74** [comment]
Seems that this works. You may need to confirm.
```
##########################################
set_online_regex='collabora/collabora-online-4$'
set_core_regex='cp-6.0$'
##########################################
```

**Comment by adiluzio** [comment]
Wow, thank you! I'll try it immediately.
Thanks again! :)

---EDIT---
For the record, my last attempt was with:
##########################################
set_online_regex='collabora/collabora-online-4$' #CODE 4 Branch
set_core_regex='cp-6.2$' #LibO 6.2.x
##########################################
deleting "with_theme=galaxy" inside default.cfg.

It compiled fine, no crashes in a day of running but i had fatal errors every time i tried to modify an odp file.
I hope that setting the core to 'cp-6.0$' will solve my problems.

**Comment by adiluzio** [comment]
With this build every time i modify a presentation file i get:

feb 28 21:44:39 debian loolwsd[21762]: | wsd/DocumentBroker.cpp:362
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-22331 2019-02-28 20:44:40.731756 [ docbroker_009 ] ERR  Invalid or unknown session [006d] to remove.| wsd/DocumentBroker.cpp:1157
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-22331 2019-02-28 20:44:40.731778 [ docbroker_009 ] ERR  No socket associated with WebSocketHandler 0x7ffbb8000ab0| ./net/WebSocketHandler.hpp:108
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-21765 2019-02-28 20:44:40.731840 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_009], started: true, finished: true| ./net/Socket.hpp:622
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-21765 2019-02-28 20:44:40.731850 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_009], started: true, finished: true| ./net/Socket.hpp:622
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-21765 2019-02-28 20:44:40.731876 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_009], started: false, finished: true| ./net/Socket.hpp:622
feb 28 21:44:40 debian loolwsd[21762]: wsd-21762-21765 2019-02-28 20:44:40.731881 [ prisoner_poll ] WRN  Waking up dead poll thread [docbroker_009], started: false, finished: true| ./net/Socket.hpp:622

EDIT
I changed nothig but now if i try to do the same thing (modify i presentation file) i get this:

feb 28 22:09:30 debian loolwsd[24068]: kit-24093-24145 2019-02-28 21:09:30.741428 [ lokit_001 ] SIG   Fatal signal received: SIGSEGV
feb 28 22:09:32 debian loolwsd[24068]: kit-24142-24176 2019-02-28 21:09:32.477098 [ lokit_002 ] SIG   Fatal signal received: SIGSEGV
feb 28 22:09:39 debian loolwsd[24068]: kit-24173-24188 2019-02-28 21:09:39.552620 [ lokit_003 ] SIG   Fatal signal received: SIGSEGV
feb 28 22:11:17 debian loolwsd[24068]: kit-24185-24207 2019-02-28 21:11:17.477795 [ lokit_004 ] SIG   Fatal signal received: SIGSEGV


Any clues?

EDIT2:
Maybe could be related to the fact that i'm using a VM (but it has 6 cores and 8 gb of ram)?

**Comment by tiredofit** [comment]
@adiluzio I have made a [Docker image](https://hub.docker.com/r/tiredofit/libreoffice-online) that has generous limits for documents and users. You can [fork](https://github.com/tiredofit/docker-libreoffice-online) and swap out the two commit hashes in the top of the Dockerfile to try out various versions to see which one works for you. So far it comes out to 2.0gb / 700mb compressed.

I wouldn't have been able to make this happen without the work of all others in this repo.

**Comment by Ark74** [comment]
> Any clues?

Not really, it works on my side.
Also I'm using Ubuntu 16.04.

**Comment by adiluzio** [comment]
Thank you to both of you.
I'll try to build some other versions of core and lool (at most another two or three attempts) and if i'll fail i will use your docker image.
Thank you again. :)
