### ISSUE TITLE
compile fails using debian buster and gcc8 / temporary workaround included

### ISSUE THREAD

**Issue by joergmschulz** [husisusi/officeonlin-install.sh#177]
what worked some weeks ago, does not work any longer. The compile of loolwsd fails:
```
Configuration:
    LOKit path              /opt/online/bundled/include
    LO path                 /opt/libreoffice/instdir
    LO integration tests    test against /opt/libreoffice/instdir
    SSL support             ssl enabled
    Debug & low security    secure mode: product build
    Anonymization           no anonymization of usernames or filenames
    Set capabilities        setcap enabled

    $ make # to compile
    $ make run # to start loolwsd

make: Verzeichnis „/opt/online“ wird betreten
make  all-recursive
make[1]: Verzeichnis „/opt/online“ wird betreten
Making all in .
make[2]: Verzeichnis „/opt/online“ wird betreten
  CXX      common/SigUtil.o
  CXX      common/Authorization.o
  CXX      net/DelaySocket.o
common/SigUtil.cpp: In function ‘void SigUtil::setFatalSignals()’:
common/SigUtil.cpp:256:16: error: ‘char* strncpy(char*, const char*, size_t)’ specified bound 256 equals destination size [-Werror=stringop-truncation]
         strncpy(FatalGdbString, streamStr.c_str(), sizeof(FatalGdbString));
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:1393: common/SigUtil.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[2]: Verzeichnis „/opt/online“ wird verlassen
make[1]: Verzeichnis „/opt/online“ wird verlassen
make[1]: *** [Makefile:2042: all-recursive] Fehler 1
make: *** [Makefile:937: all] Fehler 2
make: Verzeichnis „/opt/online“ wird verlassen
```

this fails as well with older configurations so I assume some default compiler flags to be the culprit. Does anybody have an idea here?

**Comment by Ark74** [comment]
Do you think is related to that version only?

**Comment by joergmschulz** [comment]
I can't compile on stretch currently because I'd lose my last working officeonline server. (test=buster, prod=stretch).

**Comment by joergmschulz** [comment]
confirmed. Last night I have set up a docker image of a vanilla debian stretch and there it worked (after manually installing npm using https://linuxconfig.org/how-to-install-nodejs-on-debian-9-stretch-linux ) . Here gcc 6.3.0 is used. So now we have the question: What changed, why will op cit warning be considered critical now, how can we work around this one? 

Edit: after a dist-upgrade of that docker vm to Debian buster, I have the same error. So this seems to be clear.


Edit2:

using this stanza
```
lool_configure_opts='--disable-werror'
```

in officeonline-install.cfg, it works and we get:
```
Diese Version von LibreOffice Online wird bereitgestellt von
LOOLWSD
4.0.3 (git hash: 81ea0090)
LOKit
Collabora OfficeDev 6.0-28 (git hash: 74181e6)
```


### a workaround only, we should wait for upstream to deliver source that throws no errors.

**Comment by vjpristy** [comment]
> confirmed. Last night I have set up a docker image of a vanilla debian stretch and there it worked (after manually installing npm using https://linuxconfig.org/how-to-install-nodejs-on-debian-9-stretch-linux ) . Here gcc 6.3.0 is used. So now we have the question: What changed, why will op cit warning be considered critical now, how can we work around this one?
> 
> Edit: after a dist-upgrade of that docker vm to Debian buster, I have the same error. So this seems to be clear.
> 
> Edit2:
> 
> using this stanza
> 
> ```
> lool_configure_opts='--disable-werror'
> ```
> 
> in officeonline-install.cfg, it works and we get:
> 
> ```
> Diese Version von LibreOffice Online wird bereitgestellt von
> LOOLWSD
> 4.0.3 (git hash: 81ea0090)
> LOKit
> Collabora OfficeDev 6.0-28 (git hash: 74181e6)
> ```
> 
> ### a workaround only, we should wait for upstream to deliver source that throws no errors.

thx, this works for me.
