### ISSUE TITLE
Ubuntu 18.04 LTS header Poco/Net/WebSocket.h not found

### ISSUE THREAD

**Issue by marco-aa** [husisusi/officeonlin-install.sh#180]
Dear All,

i setup a new Ubuntu 18.04 LTS server, cloned the git and run the script - i stopped/crashed with
 `checking for LibreOfficeKit/LibreOfficeKit.h... yes`
`checking Poco/Net/WebSocket.h usability... no`
`checking Poco/Net/WebSocket.h presence... no`
`checking for Poco/Net/WebSocket.h... no`
`configure: error: header Poco/Net/WebSocket.h not found, perhaps you want to use --with-poco-includes`

Addition information:  /opt/poco-1.9.0-all/Net/ contains source files but no WebSocket.h

Based on https://github.com/husisusi/officeonlin-install.sh/issues/159#issuecomment-397222660
i thought it could work ;-)

Some idea where to look ?

**Comment by marco-aa** [comment]
I changed in lib/default.cfg `poco_forcebuild=true` an re-run the script 
later i had do `sudo apt-get install npm` and ` npm install -g npm` inspired by #159 

Finaly it compiled and service is running - Please close this issue :) 
Thanks for your cool work !!!

**Comment by Ark74** [comment]
Hello @marco-aa 
Glad you found a work around to this issue, and explained the solution.

> Finaly it compiled and service is running - Please close this issue :)

Don't forget that you can close it too.
Cheers!

**Comment by marco-aa** [comment]
thx done and closed ;)
