### ISSUE TITLE
configure: error: unrecognized options: --disable-kde4

### ISSUE THREAD

**Issue by jstone1984** [husisusi/officeonlin-install.sh#181]
Running ./configure with '--disable-dbus --disable-dconf --disable-epm --disable-ext-nlpsolver --disable-ext-wiki-publisher --disable-gio --disable-gstreamer-0-10 --disable-gstreamer-1-0 --disable-gtk3 --disable-kde4 --disable-odk --disable-online-update --disable-postgresql-sdbc --disable-report-builder --disable-scripting-beanshell --disable-sdremote --disable-sdremote-bluetooth --enable-mergelibs --enable-python=internal --with-external-dict-dir=/usr/share/hunspell --with-external-thes-dir=/usr/share/mythes --with-galleries=no --with-lang= --with-linker-hash-style=both --with-system-dicts --with-theme=galaxy --without-branding --without-help --without-java --without-myspell-dicts --without-package-format --without-system-jars --without-system-libpng --without-system-libxml --without-system-poppler --without-system-postgresql --srcdir=/opt/libreoffice --enable-option-checking=fatal'
configure: error: unrecognized options: --disable-kde4
Error running configure at ./autogen.sh line 302.

**Ubuntu 16.04.6 LTS tried many times, how can I solve it?**

**Comment by joergmschulz** [comment]
remove this stanza in lib/default.cfg along with --with-theme=galaxy.
Compile will work, but see https://github.com/husisusi/officeonlin-install.sh/issues/155 ; currently I am not sure which repository is best.

**Comment by husisusi** [comment]
We should use 18.04
