### ISSUE TITLE
libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found

### ISSUE THREAD

**Issue by Ludovicis** [husisusi/officeonlin-install.sh#182]
Hello, 

I have this problem with my collabora install (found in Syslog after service loolwsd stop / service loolwsd start):
/opt/online/loolwsd: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/local/lib/libPocoNetSSL.so.60)

Someone can help me, please ? Thanks,

**Comment by joergmschulz** [comment]
Hmmm, no clue. Can you give us more info, like 
- debian version; did you update something after installing officeonline?
- did you compile the package on the same server as the server it is supposed to run on?
- did you comment out the stanza ssl_fix_dirty?
possibly it would be best to remove everything and restart a compile run again on the same machine it will be run on.
Removing would include the removal of the pinning of openssl in /etc/apt/sources.list.d/...

**Comment by Ludovicis** [comment]
Hello joergmschulz,

My debian version is Debian 4.9.110-3
I have compile the package on the same server as the server it is supposed to run on
"did you comment out the stanza ssl_fix_dirty?"
Where i can comment this stanza ssl fix, please ?
"possibly it would be best to remove everything and restart a compile run again on the same machine it will be run on."
I have test but no success, maybe i have forget to suppress one package... or folder...
"Removing would include the removal of the pinning of openssl in /etc/apt/sources.list.d/.."
I don't understand, how i can remove the pinning of openssl, please ?

**Comment by Gomez** [comment]
Got the same error some weeks ago. I suspect a debian update. Havent solved the problem instead compiled new on a updated debian box.

**Comment by Ludovicis** [comment]
OK, i have found the solution.
I installed the docker collabora online, then I retrieved the two files libPocoNetSSL.so.60 and libcrypto.so.1.0.0. Then I copy them to their respective locations.
And now no more error.
