### ISSUE TITLE
What is the process to upgrade a prior installation?

### ISSUE THREAD

**Issue by rwagnon** [husisusi/officeonlin-install.sh#186]

**Comment by joergmschulz** [comment]
be sure to have a good backup or build a second server first that runs loolwsd.
point your nextcloud to that second server.

cp /opt/online/loolwsd.xml /somewhere/safe
service loolwsd stop
rebuild the suite
copy loolwsd.xml back in place
service loolwsd start
point your nextcloud test environment to this installation
start debugging, worrying, rebuild until you have a working version
point nc prod to this working installation
do the same on the second running server

It's a good idea to always have at least two running versions.

**Comment by quenenni** [comment]
Another way to manage the upgrade process: #191
