### ISSUE TITLE
ERR  Socket #15 SSL error: SYSCALL (5). (ECONNRESET: Connection reset by peer)| ./net/SslSocket.hpp:236

### ISSUE THREAD

**Issue by titansmc** [husisusi/officeonlin-install.sh#189]
Hi,
I am running:
```
set_core_regex='cp-6.0$'
set_online_regex='collabora-online-4'
```
behind HAProxy terminating SSL in the proxy but also connecting to the backend through SSL and I still get those conn reset on the libreoffice nodes:
```
Oct 21 15:49:08 ops-office02.domain.com loolwsd[837]: wsd-00837-00896 2019-10-21 13:49:08.274082 [ websrv_poll ] ERR  Socket #15 SSL error: SYSCALL (5). (ECONNRESET: Connection reset by peer)| ./net/SslSocket.hpp:236
```
Does anyone have an idea about what could be causing the issue? It might be coming from the health checks from HAProxy, but I can still see the Libreoffice nodes fine from HAProxy.

**Comment by Ya-Ri** [comment]
hi, happy new year, same issue here, how do you manage to solve it?

**Comment by titansmc** [comment]
no solution found yet, it just works with errors...

**Comment by husisusi** [comment]
old
