### ISSUE TITLE
Lool on Debian 10 buster. Working after few modifications

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#190]
I succeeded to have it working on a newly install Debian 10.

Only few changes in 1 file to have the script working and a specific configuration to have the script select the right branch / versions of the repos.

In file bin/systemSetup.sh (line 58):
* Replace this
```
if [ "${DIST}" = "Debian" ]; then
  if [ "${CODENAME}" = "stretch" ];then
    # ssl_fix_dirty no longer necessary
    DIST_PKGS="${DIST_PKGS} openjdk-8-jdk"
    DIST_PKGS="${DIST_PKGS} libpng16.16"
    DIST_PKGS="${DIST_PKGS} libpng-dev"
  else
    DIST_PKGS="${DIST_PKGS} openjdk-7-jdk"
    DIST_PKGS="${DIST_PKGS} libpng12-0"
    DIST_PKGS="${DIST_PKGS} libpng12-dev"
  fi
fi
```
by this:
```
if [ "${DIST}" = "Debian" ]; then
  if [ "${CODENAME}" = "stretch" ];then
    # ssl_fix_dirty no longer necessary
    DIST_PKGS="${DIST_PKGS} openjdk-8-jdk"
    DIST_PKGS="${DIST_PKGS} libpng16.16"
    DIST_PKGS="${DIST_PKGS} libpng-dev"
  elif [ "${CODENAME}" = "buster" ];then
    DIST_PKGS="${DIST_PKGS} openjdk-11-jdk"
    DIST_PKGS="${DIST_PKGS} libpng16.16"
    DIST_PKGS="${DIST_PKGS} libpng-dev"
  else
    DIST_PKGS="${DIST_PKGS} openjdk-7-jdk"
    DIST_PKGS="${DIST_PKGS} libpng12-0"
    DIST_PKGS="${DIST_PKGS} libpng12-dev"
  fi
fi
```
* Also in that file, as nodejs v6 is not supported anymore, I installed the nodejs version from buster (v10). Replace this
```
if [ ! -f /etc/apt/sources.list.d/nodesource.list ]; then
  curl -sL https://deb.nodesource.com/setup_6.x | bash -
  apt-get install nodejs -y
fi
```
by this
```
if [ "${DIST}" = "Debian" ]; then
  if [ "${CODENAME}" = "buster" ];then
    apt-get install nodejs -y
  else
    if [ ! -f /etc/apt/sources.list.d/nodesource.list ]; then
      curl -sL https://deb.nodesource.com/setup_6.x | bash -
      apt-get install nodejs -y
    fi
  fi
fi
```
* I had to install npm manually. But the npm version from official debian repo (5.8.0+ds6-4) is not compatible with the nodejs version (10.15.2~dfsg-2).
To install a more recent version of npm (v6.13.6), still in the same file :
```
curl https://www.npmjs.com/install.sh | sh
```
You can add this line just after the previous change (apt-get install nodejs -y in "buster" bloc).
* And finally, I had to install the package python3-polib
```
apt install python3-polib -y
```
You can also add this line just after the previous change (apt-get install nodejs -y in "buster" bloc).

With these changes, the script is working.

But by default, the script doesn't take the right Lool branch (collabora-online-4).
I succeeded to set it to a good branch (collabora-online-4-0) and now I have Lool working
```
LOOLWSD
4.0.9 (git hash: 956c17af)
LOKit
Collabora OfficeDev 6.2-3 (git hash: 02b9ea6)
```
For the exact configration to select that branch, check this post that keeps tracks of working configs: #188

**Comment by NateTheSage** [comment]
I just saw this today, I'm going to attempt it on my live Nextcloud instance to see if it works. If it does, I'll tweak it a bit for modern standards and see about a pull request.

**Comment by NateTheSage** [comment]
@quenenni Did you get any really weird issues where if you tried to let the script clone the repositories it didn't work, yet when you ran the clone manually it worked?

I've been sitting here running two different terminal sessions with a manual clone working and the clone via the script sitting there and apparently doing nothing.

**Comment by joergmschulz** [comment]
@natethesage
cloning the LO repository can take a while depending on your bandwidth and the state of the networks
```

#  (this one is compulsory)
lool_src_branch='distro/collabora/collabora-online-4-0'


#### LibreOffice parameters ###
#lo_src_repo='https://github.com/LibreOffice/core.git'
lo_src_branch='libreoffice-6-3-4' # a existing branch name. # THIS WILL be overriden by the set branch
lo_src_commit='60da17e045e08f1793c57c00ba83cdfce946d0aa' # the short/full id of a git commit
lo_src_tag='libreoffice-6-3-4' # a tag in the repo git
# lo_src_tag='cp-6.0-34' # a tag in the repo git
lo_forcebuild=false # force compilation
#lo_req_vol=11000 # minimum space required for LibreOffice compilation, in MB
#lo_mini=true
#lo_configure_opts='' #comma separated options names
lo_non_free_ttf=true # add Microsoft fonts to Ubuntu

#### POCO parameters ###
poco_version=$poco_version_latest #latest releases available
#poco_forcebuild=false
#poco_req_vol=550 # minimum space required for Poco compilation, in MB

#### LibreOffice Online parameters ###
lool_src_repo="https://github.com/LibreOffice/online.git"
lool_src_branch='distro/collabora/collabora-online-4-0' # a existing branch name. # THIS WILL be overriden by the set branch

```

**Comment by NateTheSage** [comment]
Of course of course, but when an `ls -hal` in `/opt/libreoffice` shows just the `.git` folder, while the manual operation is already 1GB in, clearly I've done something wrong. :laughing: 

I will try your config you posted there and see if that helps.

**Comment by NateTheSage** [comment]
Wow, guess I'm just used to seeing output from `git`.

Riddle me this, though...

```
checking which themes to include... configure: error: Unknown value for --with-theme: galaxy
Error running configure at ./autogen.sh line 296.
```

**Comment by joergmschulz** [comment]
> Unknown value for --with-theme: galaxy

been there. 
lib/default.cfg:
```
declare -r lo_mini_opts='disable-dbus, disable-dconf, disable-epm,
disable-evolution2, disable-ext-nlpsolver, disable-ext-wiki-publisher,
disable-firebird-sdbc, disable-gio,  disable-gstreamer-1-0,
disable-gtk, disable-gtk3,  disable-odk, disable-online-update,
disable-pdfimport, disable-postgresql-sdbc, disable-report-builder, disable-scripting-beanshell,
disable-scripting-javascript, disable-sdremote, disable-sdremote-bluetooth,
enable-extension-integration, enable-mergelibs, enable-python=internal,
enable-release-build, with-external-dict-dir=/usr/share/hunspell,
with-external-hyph-dir=/usr/share/hyphen, with-external-thes-dir=/usr/share/mythes,
with-fonts, with-galleries=no, with-lang=, with-linker-hash-style=both, with-system-dicts,
with-system-zlib,  without-branding, without-help, without-java,
without-junit, without-myspell-dicts, without-package-format, without-system-jars,
without-system-jpeg, without-system-libpng, without-system-libxml,
without-system-openssl, without-system-poppler, without-system-postgresql'
```

**Comment by NateTheSage** [comment]
Ahhh, and the insight is further shared! I'll give that a shot tonight if not tomorrow.

**Comment by NateTheSage** [comment]
I got closer. Alas, time prevented me from responding sooner.

```
LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}"/opt/libreoffice/instdir/program:/opt/libreoffice/instdir/program":/opt/libreoffice/workdir/UnpackedTarball/icu/source/lib /opt/libreoffice/workdir/UnpackedTarball/firebird/gen/Release/firebird/bin/isql -q -i /opt/libreoffice/workdir/UnpackedTarball/firebird/src/dbs/metadata.sql                                                                                  
can't format message 17:0 -- message file /opt/libreoffice/workdir/UnpackedTarball/firebird/gen/Release/firebird/firebird.msg not found                                                                        
Unable to complete network request to host "localhost".
-Failed to establish a connection.
can't format message 17:120 -- message file /opt/libreoffice/workdir/UnpackedTarball/firebird/gen/Release/firebird/firebird.msg not found                                                                      
make[5]: *** [Makefile:326: metadata.fdb] Error 1
make[5]: Leaving directory '/opt/libreoffice/workdir/UnpackedTarball/firebird/gen'
make[4]: *** [Makefile:176: master_process] Error 2
make[4]: Leaving directory '/opt/libreoffice/workdir/UnpackedTarball/firebird/gen'
make[3]: *** [Makefile:66: firebird] Error 2
make[3]: Leaving directory '/opt/libreoffice/workdir/UnpackedTarball/firebird/gen'
make[2]: *** [Makefile:6: firebird] Error 2
make[2]: Leaving directory '/opt/libreoffice/workdir/UnpackedTarball/firebird'
make[1]: *** [/opt/libreoffice/external/firebird/ExternalProject_firebird.mk:41: /opt/libreoffice/workdir/ExternalProject/firebird/build] Error 1                                                              
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:286: build] Error 2
```

**Comment by joergmschulz** [comment]
hmmm. while compiling, in another window:
```
cd /opt
find ./ -iname firebird
```

> ./libreoffice/external/firebird
> ./libreoffice/connectivity/source/drivers/firebird
> ./libreoffice/connectivity/registry/firebird

obviously this is called at some time during compilation. Do you use SElinux and block some ports? Just guessing.

**Comment by NateTheSage** [comment]
Nope, not using SELinux and not blocking ports. At least locally, although I have no idea why it might try to reach out to the Internet.

Edit: It looks like for some reason Firebird just doesn't start. Let me see if I can figure that out.

Edit again: The file is in fact missing when I go to look.

**Comment by joergmschulz** [comment]
just guessing around. Had that a long time ago. 
Did you install npm extra in advance? This seemed to be missing in the script at some time.

**Comment by NateTheSage** [comment]
I will double check, I'm pretty sure it is in fact installed.

Edit: I get a failure to install `puppeteer@1.20.0`, I think it's because `2.1.1` is current.

Further edit: I had to do a `-g puppeteer` in addition to `--unsafe-perms=true` and `--allow-root` to get it to work. I'll update my status.

**Comment by NateTheSage** [comment]
Still same error. There must be something I'm missing with Firebird.

**Comment by dieg0nob** [comment]
i have this error:
From https://github.com/LibreOffice/core.git
From https://github.com/LibreOffice/online
   7ba4e9dd2..e99f0da28  master     -> origin/master
From https://github.com/LibreOffice/online.git
Reading package lists...
Building dependency tree...
Reading state information...
Package nodejs-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libnode-dev

E: Package 'nodejs-dev' has no installation candidate


how can i fix it ?

**Comment by quenenni** [comment]
@dieg0nob 
Did you try on a Debian Buster?
nodejs-dev doesn't exist anymore in buster and I can find any reference as a dependancy.

Did you make all the changes I show in the first post?

Dis you try to install manually the package libnode-dev?

The error seems to come from the file "bin/systemSetup.sh", with all the apt install stuff.
Can you try to install all the packages manually?

**Comment by dieg0nob** [comment]
> @dieg0nob
> Did you try on a Debian Buster?
> nodejs-dev doesn't exist anymore in buster and I can find any reference as a dependancy.
> 
> Did you make all the changes I show in the first post?
> 
> Dis you try to install manually the package libnode-dev?
> 
> The error seems to come from the file "bin/systemSetup.sh", with all the apt install stuff.
> Can you try to install all the packages manually?

i edited bin/onlinePrep.sh
and remove nodejs-dev in the line apt-get install and edited libpococrypto50 with libpococrypto60 because ask me to install libpococrypto50 and this package isn`t in buster
