### ISSUE TITLE
Managing multiple Lool instances

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#191]
I'm using Debian 10 (buster).

-------------------------------------

The most annoying part I find is the process to update the Lool instance or have multiple independant instances to use the load balancing or a backup system in Nginx.<br />
Up to now, I installed a new VPS, compiled and tested a new version and when happy, switch the DNS.. But it's painful.<br />
I want to be able to keep an existing and functioning Lool instance while compiling another one without interference. <br />
And if good, just update the nginx vhost to point to the new version.

To have that, I needed first to be sure there are no commun folders / files used by several instances.

In example:
You compile LO in /opt/libreoffice. At the end of the process, it creates a symlink in /usr/bin to link the soffice program.
Then you compiled another version and at the end, it creates the same symlink (and thus removing the old one).
If Lool use /usr/bin/libreoffice as a reference to LO, that would quickly brings problems.

**The 3 components to compile:**
- LibreOffice (LO).
From what I understand, all is compiled inside the LO folder and LOOL references /opt/libreoffice/instdir/ for LO.
- Poco:
I'm not sure yet. I did all my tests with the same Poco version.
- Online (Lool):
When Lool finished compiling, you'll have files in:
  * /etc/loolwds/
  * /usr/bin/{loolconfig/loolconvert/..}
  * /usr/share/man | /usr/share/doc/ | /usr/share/loolwsd/
  * /var/cache/loolwsd/

In order to have these files outside system dirs, you can use the variable:
```
lool_prefix=
lool_eprefix=
lool_sysconfdir=
lool_localstatedir=
```
Ie, if I put /opt/online_common/online1/, all the common files will be in sub-folders of /opt/online_common/online1/ (like /opt/online_common/online1/etc/loolwsd/..)

All the options I showed above are not taken into account by default.
You have to modify also the file bin/onlineBuild.sh and add the line for the option lool_eprefix:
```
[ -n "${lool_prefix}" ] && lool_configure_opts="${lool_configure_opts} --prefix=${lool_prefix}"
[ -n "${lool_eprefix}" ] && lool_configure_opts="${lool_configure_opts} --exec-prefix=${lool_eprefix}"   # <- add this line
[ -n "${lool_sysconfdir}" ] && lool_configure_opts="${lool_configure_opts} --sysconfdir=${lool_sysconfdir}"
```

**Having an indice to easily compile a new version**
In order to easily compile a new version, or update an existing one, I preferred to play with an indice in the config file:<br />
Ie, for 3 instances, I'll have such a folder structure:
```
/opt/libreoffice1/
/opt/libreoffice2/
/opt/libreoffice3/
/opt/online1/
/opt/online2/
/opt/online3/
/opt/online_exec/online1/
/opt/online_exec/online2/
/opt/online_exec/online3/
```
To have that, first adapt officeonline-install.cfg:
```
###########################
###  COMPIL NUMBER #######
###########################
compil_version=1
```
( Somewhere on top of the file:)

Then, modify all these options like this (adapt the folder where you want to place all the programs):
```
lo_dir="/opt/libreoffice${compil_version}"

lool_dir="/opt/online${compil_version}"

lool_logfile="/var/log/loolwsd${compil_version}.log"
lool_prefix="/opt/online_exec/online${compil_version}"
lool_eprefix="/opt/online_exec/online${compil_version}"
lool_sysconfdir="/opt/online_exec/online${compil_version}/etc"
lool_localstatedir="/opt/online_exec/online${compil_version}/var"

loolwsd_service_name="loolwsd${compil_version}"
```
And in the file bin/onlineInstall.sh:
```
ExecStartPre=/bin/mkdir -p ${lool_localstatedir}/cache/loolwsd
ExecStartPre=/bin/chown lool: ${lool_localstatedir}/cache/loolwsd
```

Just by incrementing / adapting the var compil_version, you'll be able to compile new independant versions of Lool.

**Manual intervention in certain case**
I searched a lot but couldn't find how to pass as a parameter the ports the Lool service will use.
Any tips on that matter is welcome.

By default, it's 9980 and 9981 and it's defined in the file common/Common.hpp (in online repo)

For the first compilation, nothing to adapt, the service will run on these 2 ports.

But for the other compilations, you have to modify them manually before starting the compilation process.

I modified the script bin/onlinePrep.sh to force a pause and let me choose the branch / commit manually (and modify the Common.hpp if needed) before going on with the compilation.
```
if [ -d ${lool_dir} ]; then
  cd ${lool_dir}
else
  git clone ${lool_src_repo} ${lool_dir}
  cd ${lool_dir}
fi

# Changes start here
if [[ ! -z "${lool_prefix}" && ! -d "${lool_prefix}" ]]; then
  mkdir -p "${lool_prefix}"
fi

kwak=""
echo
echo "Time to go change the repo to the commit you want"
echo
while [ "$kwak" != "kwak" ] && [ "$kwak" != "exit" ] && [ "$kwak" != "last" ]
do
  echo -n "  Write 'last' to use the last commit, 'kwak' to go on with the defined commit or 'exit' to quit : "
  read kwak
  echo
done

if [[ "$kwak" == "exit" ]]; then
  exit
elif [[ "$kwak" == "last" ]]; then
  declare repChanged
  eval "$(SearchGitCommit $SearchGitOpts)"
  if [ -f ${lool_dir}/loolwsd ] && $repChanged ; then
    lool_forcebuild=true
  fi
fi
```
So, before typing 'kwak', go edit the file common/Common.hpp and use other port numbers.

I did lots of tests like installing a Lool at a version X (with LO at version XX), then another one at version Y (with LO at version XY), then remove version Y and version X was still working.<br /> 
Tried all sort of tests of that kind and all seems good.

I configured my nginx vhost file to use my second instance as a backup, but you can play with load-balancing too.
```
# Backup instance
upstream lool {
    server localhost:9980;
    server localhost:9982 backup;
}

# Load-balancing
upstream lool {
    ip_hash;
    server localhost:9980;
    server localhost:9982;
}
```

It's several days I have in production 2 instances of Lool and up to now, no problem.

**Potential problems**
One thing I don't really understand why..
I defined the cache folder to be in "/opt/online_exec/online${compil_version}/var/cache/loolwsd/, at least for the Lool service.

But I see the all the cache files are managed in /var/cache/loolwsd/ for all the Lool instances and the folders /opt/online_exec/online${compil_version}/var/cache/loolwsd/ stay empty.

Either the cache is used by LibreOffice and not Lool (I didn't defined specific location for LO cache), or Lool is not using correctly that parameter.

Despite that, I wonder is it's not better to have a common cache folder, mostly when you're going the load-balancing way.

I didn't see any problem up to now, but any tips / reflexion on that matter is welcomed.

**Comment by quenenni** [comment]
Just remember that the correct place for the loolwsd.xml config file is now /opt/online_exec/online${compil_version}/etc/loolwsd/loolwsd.xml

And to restart the services, it's:
```
systemctl restart loolwsd1
systemctl restart loolwsd2
systemctl restart loolwsd3
...
```

**Comment by Ark74** [comment]
I do maintenance of locally build php versions tracking the latest and greatest, the approach I've taken to co-exist several php versions is using different ports.

I keep 2 varians of each version, something like 
* 7.4.x
* 7.4.x_mbuild (as in maintenance build)

According to the final app using the instance, the switch can be a little daunting, but in case with a certain cloud app I've used systemd to help in the process of switching from the current version to the maintenance version one that is already compiled.

In other words, only after the build is successfully built and is ready, then it changes the port used on the webserver that it's listening.

That way, you avoid changing DNS settings and only build locally.
In case of LibO Online, I'm not sure this is the best option since the build process is very resource consuming.

File directory, ports, symlinks and systemd got the task done, since loolwd is a more complete approach maybe is not that simple, but I still believe the approach could work.

That may affect user performance but prevent downtimes.

**Comment by Ark74** [comment]
> Just remember that the correct place for the loolwsd.xml config file is now /opt/online_exec/online${compil_version}/etc/loolwsd/loolwsd.xml

Really?

I still use /etc fine and dandy :)

**Comment by quenenni** [comment]
@Ark74 

If you use the option:
 lool_sysconfdir="/opt/online_exec/online${compil_version}/etc"
then the loolwsd.xml file will be there.

If you're not using that option, in case of multiple instance of LOOL, both instances will use the same file in the /etc/loolwsd folder..
When you'll compile a new version, the first step, cleaning the old instance, will delete the file /etc/loolwsd/loolwsd.xml file.

**Comment by Ark74** [comment]
@quenenni oh I see. that's the reason then.
I'm still using separate servers when upgrading to a newer release

**Comment by quenenni** [comment]
Just to give some feedback.

After few months using the last version, I launched the script to have a third Lool last week to more recent commits..
Success. I have 3 different Lool working on my server(only 2 active).

I feel my multi Lool is working fine.
