### ISSUE TITLE
Ubuntu 16.04 issues

### ISSUE THREAD

**Issue by rwagnon** [husisusi/officeonlin-install.sh#192]
Thank you to everyone for creating this great project.

I'm having the following problem using the cfg listed in the Wiki.

I've tried a lot of variations, but I get the following error during the online compilation:
[Lool-compilation.log](https://github.com/husisusi/officeonlin-install.sh/files/4200361/Lool-compilation.log)

make: Entering directory '/opt/online'
make  all-recursive
make[1]: Entering directory '/opt/online'
Making all in .
make[2]: Entering directory '/opt/online'
  CXX      net/clientnb.o
  CXX      common/loolwsd_fuzzer-Crypto.o
  CXX      wsd/loolwsd_fuzzer-Admin.o
  CXX      wsd/loolwsd_fuzzer-AdminModel.o
  CXX      wsd/loolwsd_fuzzer-Auth.o
In file included from wsd/AdminModel.cpp:12:0:
wsd/AdminModel.hpp:291:10: error: ‘list’ in namespace ‘std’ does not name a template type
     std::list<unsigned> _memStats;
          ^~~~

Additional, apparently related errors occur.

Has anyone seen this?  It feels like a bad .h file is on the system or that it isn't honoring std=c++11.

It installed gcc:
   gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

uname -a:
    Linux myfakeservername 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rwagnon** [comment]
As a test, I compiled test.cpp:

#include <stdio.h>

#include <algorithm>
#include <iostream>
#include <list>

int main(void) {
        printf("Hello World\n");

    // Create a list containing integers
    std::list<unsigned> l = { 7, 5, 16, 8 };

    // Add an integer to the front of the list
    l.push_front(25);
    // Add an integer to the back of the list
    l.push_back(13);

}

with g++ test.cpp and g++ -std=c++11 test.cpp

Both compiled and executed fine.

**Comment by rwagnon** [comment]
I don't understand how this can be an issue across many versions of loolwsd and that it doesn't bother other people, but I fixed it.

Add #include list to AdminModel.hpp. I mean anglebracketlistcloseanglebracket.  Then did a manual make outside the script system.

Maybe someone can explain the behavior.  At least I have a workaround that people can use.  Seems it hasn't affected other people.

**Comment by Ark74** [comment]
The last working configuration on the wiki doesn't state the poco version.
Please set it to 1.9.4 and try again with the normal configuration, take into account that this project have many components working together and changes might break working instances.

Regards

**Comment by sefai** [comment]
> The last working configuration on the wiki doesn't state the poco version.
> Please set it to 1.9.4 and try again with the normal configuration, take into account that this project have many components working together and changes might break working instances.
> 
> Regards

That's what I've done two weeks ago. I was planning to open an issue about this but it seems I was late.

By the way I've used this script on Ubuntu 18.04; to make it work I manually installed npm and changed this PoCo version. Everything else is OK. So I have loolwsd running on an Ubuntu 18.04.

Regards,

**Comment by rwagnon** [comment]
It seems crazy, but POCO-1.9.4 seems to override the std::list feature.  Adding the include above allows more current POCO.  I don't know the consequences of using the alternate std::list or of using 1.9.10+.
