### ISSUE TITLE
Unable to locate package libssl1.0-dev

### ISSUE THREAD

**Issue by XUBIUM** [husisusi/officeonlin-install.sh#193]
Hello, 

I've tried 2 times to compile on Ubuntu 16.04.6 x64 (I think Ubuntu 16.04 is the supported version, right?) but the compilations ends after several hours with the error at the end of this message.

I have setup the config as stated in https://github.com/husisusi/officeonlin-install.sh/wiki and I also set the poco version to1.9.4 as recommended at https://github.com/husisusi/officeonlin-install.sh/issues/192 (not setting the poco version also ends in error, a different one)

What am I missing? Thanks for the help!

make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/opt/poco-1.9.4-all/Redis'
mkdir -p /usr/local/include/Poco
mkdir -p /usr/local/lib
mkdir -p /usr/local/bin
for comp in Foundation Encodings XML JSON Util Net Crypto NetSSL_OpenSSL Data Data/SQLite Zip PageCompiler PageCompiler/File2Page Redis ; do \
        if [ -d "/opt/poco-1.9.4-all/$comp/include" ] ; then \
                cp -Rf /opt/poco-1.9.4-all/$comp/include/* /usr/local/include/ ; \
        fi ; \
        if [ -d "/opt/poco-1.9.4-all/$comp/bin" ] ; then \
                find /opt/poco-1.9.4-all/$comp/bin -perm -700 -type f -exec cp -f {} /usr/local/bin \; ; \
        fi ; \
done
find /opt/poco-1.9.4-all/lib/Linux/x86_64 -name "libPoco*" -type f -exec cp -f  {} /usr/local/lib \;
find /opt/poco-1.9.4-all/lib/Linux/x86_64 -name "libPoco*" -type l -exec cp -Rf {} /usr/local/lib \;
Cloning into '/opt/online'...
Switched to a new branch 'distro/collabora/collabora-online-4-0-4'
Branch distro/collabora/collabora-online-4-0-4 set up to track remote branch distro/collabora/collabora-online-4-0-4 from origin.
Selected Tag: cp-4.0.4-3, origin/distro/collabora/collabora-online-4-0-4 305832f
HEAD is now at 305832f Bump package version to 4.0.4-3
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libssl1.0-dev
E: Couldn't find any package by glob 'libssl1.0-dev'
E: Couldn't find any package by regex 'libssl1.0-dev'
E: Unable to locate package libpococrypto50

**Comment by joergmschulz** [comment]
see PR  #194

**Comment by Ark74** [comment]
@XUBIUM Ubuntu 18.04 is also proven to work.

**Comment by XUBIUM** [comment]
Yes, I have been able to compile in 18.04 without doing PR #194 ... I was compiling already when I got the 1st answer, and it appears to have finished withour issues. I'll configure the nginx and SSL and will confirm here if everything is ok.

**Comment by XUBIUM** [comment]
I can confirm that it is working perfectly with 1804... thanks for the help!
