### ISSUE TITLE
Translation loolwsd 4.2 incomplete

### ISSUE THREAD

**Issue by dieg0nob** [husisusi/officeonlin-install.sh#195]
i'm testing lo_src_tag='cp-6.2-5' with lool_src_tag='CODE-4.2.0-6' in debian buster
for the moment it's working fine, but i want to know how can i translate to spanish all the loolwsd, some part is in spanish.

![collabora1](https://user-images.githubusercontent.com/29979144/76421668-c7f76900-6382-11ea-8f61-ece2adf62555.png)

**Comment by husisusi** [comment]
There is nothing the script can do about this issue.
I have the same issue on 6.4.6.
