### ISSUE TITLE
build possible w/o building poco

### ISSUE THREAD

**Issue by joergmschulz** [husisusi/officeonlin-install.sh#198]
Just detected that according to the official build documentation in 
https://wiki.documentfoundation.org/Development/BuildingOnline#Environment_setup
poco can be used from the distribution just like demonstrated in the official build script /opt/online/docker/l10n-docker-nightly.sh

Do you think it is worthwile removing the poco part out of this script and using the distrib libpoco-dev libraries?

**Comment by husisusi** [comment]
@joergmschulz, I need 4 Minutes with the script to install Poco (16 CPUs). I don't think that would be a benefit.
Using another script to build it on top of Docker is not the best practice.

**Comment by joergmschulz** [comment]
I think I made myself not clear. The idea was not to use the docker build script but to use the pocolibs from the distribution instead of using a selfcompiled poco. This would reduce complexity. 
On the other hand: when we use selfcompiled poco libraries we are sure to have a consistent combination of all the selfcompiled stuff. So you may still be right to self-compile as much as possible.
