### ISSUE TITLE
Strange loop

### ISSUE THREAD

**Issue by joergludwig** [husisusi/officeonlin-install.sh#2]
The build script contains multiple calls of `for dir in ./*/`. This seems very strange to me.

If you call the script from a directory without subdirectories, it will run the command inside the loop once, which is fine:

```
office.test /root # for dir in ./*/ ; do (cd "$oo" && echo npm install -g npm); done
npm install -g npm
```

But if you call the script from a directory with subdirectories, it will run the loop contents multiple times:

```
office.test / # for dir in ./*/ ; do (cd "$oo" && echo npm install -g npm); done
npm install -g npm
npm install -g npm
npm install -g npm
[...]
```

I cannot believe this is intended.

**Comment by vClouds** [comment]
Well, I have tried the script but couldn't continue after continous 7-hours
It's my first time to see my CPU jumps to 180%!

I can propose that, not to start from scratch, WE NEED the BABY not the PAIN!
Why not to start from collabora packages and let's compile loolwsd cause i think collabora people some how locked something which results in non-functional installs using whatever docker-level or system-level.

packages are already available there in deb format,
echo "deb https://www.collaboraoffice.com/apt-poco/ /" >> /etc/apt/sources.list.d/collabora.list
echo "deb https://collaboraoffice.com/repos/CollaboraOnline/CODE /" >> /etc/apt/sources.list.d/collabora.list

It's clear that, collabora people were behind introducing online concept for libreoffice and hence that packages should be equivalent libreoffice core/online repos.

Please introduce a new version of this script.

**Comment by husisusi** [comment]
It was a stupid loop!
