### ISSUE TITLE
Multiple editors "crashes" loolwsd

### ISSUE THREAD

**Issue by rwagnon** [husisusi/officeonlin-install.sh#200]
Multiple editors "seems" to work, but rapidly stops working.

Contents of officeonline-install.cfg
lo_src_repo='https://github.com/LibreOffice/core.git'
lool_configure_opts='--disable-werror'
set_version='cp-4.2.0-4'
lool_src_branch='distro/collabora/co-4-2-0'
lo_src_branch='libreoffice-6-3-4' # a existing branch name. # THIS WILL be overriden by the set branch
lo_src_commit='60da17e045e08f1793c57c00ba83cdfce946d0aa' # the short/full id of a git commit
lo_src_tag='libreoffice-6-3-4' # a tag in the repo git

lo_forcebuild=false # force compilation
lo_non_free_ttf=true # add Microsoft fonts to Ubuntu
poco_version=$poco_version_latest #latest releases available
lool_src_repo="https://github.com/LibreOffice/online.git"
lool_src_branch='distro/collabora/collabora-online-4-0' # a existing branch name. # THIS WILL be overriden by the set branch

UI problem example in Calc (similar in Writer) for two browsers with same document open:

In one browser, the client cell is bold, in the other no cell is bold.
Clicking cells in one browser moves the cell indicators in the left and top border.
Editting a cell changes both values.
Closing one document is ok, but doesn't save values.
Re-opening the closed document is ok, but doesn't show values.
Closing both documents prevents either browser from opening the document again.  Both show a "shell" of lool, but not app contents.
Other documents can still be opened.
Restarting loolwsd allows the document to be opened again.

Error Log:
it-03771-03783 2020-03-31 06:22:39.049459 [ kitbroker_001 ] ERR  No socket associated with WebSocketHandler 0x7f180034d0c0| ./net/WebSocketHandler.hpp:125
kit-03771-03783 2020-03-31 06:22:39.861782 [ kitbroker_001 ] ERR  Document [/index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00] is not loaded.| kit/Kit.cpp:1935
kit-03771-03783 2020-03-31 06:22:39.861995 [ kitbroker_001 ] ERR  Session::handleInput: Exception while handling [mouse type=move x=29325 y=110 count=1 buttons=0 modifier=0]: Document /index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00 is not loaded.| common/Session.cpp:242
kit-03771-03783 2020-03-31 06:22:41.283084 [ kitbroker_001 ] ERR  Document [/index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00] is not loaded.| kit/Kit.cpp:1935
k
...
wsd-03745-03775 2020-03-31 06:22:45.973201 [ websrv_poll ] WRN  DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00] that is marked to be destroyed. Rejecting client request.| wsd/LOOLWSD.cpp:1698
wsd-03745-03775 2020-03-31 06:22:45.973299 [ websrv_poll ] ERR  Error while handling Client WS Request: Failed to create DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00].| wsd/LOOLWSD.cpp:2734
wsd-03745-03775 2020-03-31 06:22:45.973320 [ websrv_poll ] ERR  #23: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1082
wsd-03745-03775 2020-03-31 06:22:45.973349 [ websrv_poll ] ERR  #23: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1082
wsd-03745-03775 2020-03-31 06:22:45.973917 [ websrv_poll ] ERR  #23: attempted to remove: 908 which is > size: 0 clamped to 0| ./net/Socket.hpp:951
wsd-03745-03775 2020-03-31 06:22:45.973969 [ websrv_poll ] ERR  #23: Wrote outgoing data -1 bytes. (EPIPE: Broken pipe)| ./net/Socket.hpp:1082
wsd-03745-03775 2020-03-31 06:22:47.215321 [ websrv_poll ] WRN  DocBroker with docKey [/index.php/apps/richdocuments/wopi/files/8195_ocxpsqjx6v00] that is marked to be destroyed. Rejecting client request.| wsd/LOOLWSD.cpp:1698

**Comment by husisusi** [comment]
Please try the last Version.
