### ISSUE TITLE
[SOLVED] Error Editing Docs with ä,ö,ü etc.

### ISSUE THREAD

**Issue by Alternativend** [husisusi/officeonlin-install.sh#203]
Hello guys,
i have some trouble editing documents with Collabora inside my Nextcloud when there are special characters, for instance in German we have ö,ü and ä. 

Im not able to edit those documents. 

What goes wrong there?

I still have a little issue here with special characters in the German language, like äöü.

```
root@collab:~# su lool
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

```
What can i do about it?

I build LOOL with this parameters:

```
allowed_domains="nextcloud.mydomain.de"

set_online_regex='collabora/code-4.2' 

lo_src_branch='distro/collabora/cp-6.2'
lo_src_tag='cp-6.2-5' 
lo_dir="/opt/libreoffice"

poco_forcebuild=true

lool_src_branch='distro/collabora/code-4.2.1-4'
lool_src_tag='CODE-4.2.1-4' 
lool_dir="/opt/lool" 
lool_configure_opts='--disable-werror --with-lokit-path=/opt/libreoffice/include' 
lool_forcebuild=true

```

Thanks!

**Comment by Alternativend** [comment]
So i partially solved the issue.

I ended up with this config in which i added the _--with-lang=de_ option and i found a really helpful Blog entry (https://markus-blog.de/index.php/2018/09/10/how-to-deploy-collabora-online-office-without-docker-in-plesk-and-connect-to-nextcloud-on-ubuntu/) from which i picked up just one line actually:

`apt install hunspell locales-all hunspell-de-de`

After i have done that i could compile everything and resulted with this versions and NO problems opening any kind of document, even with ö,ä,ü.  

![loolversion](https://user-images.githubusercontent.com/1799441/80608904-c4ee3000-8a37-11ea-8ae3-50a148dc8364.png)


```
allowed_domains="CLOUD.DOMAIN.de"

set_online_regex='collabora/code-4.2' 

lo_src_branch='distro/collabora/cp-6.2'

lo_src_tag='cp-6.2-8' 

lo_dir="/opt/libreoffice"
lo_forcebuild=true #force compilation
lo_non_free_ttf=true # add Microsoft fonts to Ubuntu


poco_version=1.9.4 #$poco_version_latest #latest releases available

poco_forcebuild=true

lool_src_branch='distro/collabora/code-4.2.1-4'
lool_src_tag='CODE-4.2.1-4' 
lool_dir="/opt/lool" 
lool_configure_opts='--disable-werror --with-lokit-path=/opt/libreoffice/include --with-lang=de' 
lool_forcebuild=true

```
There are just two little things i couldn´t solve so far.  The first thing is that the sidebar has not the right language... Anyone who can tell me how to change that one?

And the second thing is that he picks the wrong language for newly created documents. It should pick german and everything is configured so as well of course, but not for Collabora it seems... Would love to get some hints on this one too.

Thanks a lot!

**Comment by ibeardslee** [comment]
The wrong language for the newly created documents will be from the default language of your Document template.

It is something I have been trying to find time to put aside to investigate further, but having no luck (find the time).  I did a preliminary look for default.ott, but couldn't find anything obvious that would solve my problem with it.

**Comment by Alternativend** [comment]
@ibeardslee 
So you haven´t solve it either to this day?

**Comment by ibeardslee** [comment]
No I haven't.  But have a vague idea where to look when I have head space to dig further.
Optimally (also long term) should be able to get the building of it to help set that default language of the new documents.

**Comment by quenenni** [comment]
1. When I compiled last week a new Lool, I tried with the param " --with-lang=de", but it's not a valid param.
I saw the error when it was compiling (sorry, I don't have anymore the compilation log files, but I'm certain I saw it).
So I don't think that was that that fix the problem.

2. Concerning the language of newly created documents, you have to create a libre office template where you set the language you want and then add it to your cloud.

* Create a new document in your Libre Office Writer -> set the language -> save it as a template (.ott extension)
* Go to your cloud parameters page -> Lool (in administration section, not personal section if you want that for everyone)
* Click on the '+' right of "Global templates" and add yours.

Now when you create a new document in your cloud, it will ask you what template you want to use.

**Comment by Alternativend** [comment]
>     * Create a new document in your Libre Office Writer -> set the language -> save it as a template (.ott extension)
> 
>     * Go to your cloud parameters page -> Lool (in administration section, not personal section if you want that for everyone)
> 
>     * Click on the '+' right of "Global templates" and add yours.
> 
> 
> Now when you create a new document in your cloud, it will ask you what template you want to use.

You are right, that works. You could also set the default font with this and many more things, i guess.
