### ISSUE TITLE
I build a docker image and pushed it to docker hub.

### ISSUE THREAD

**Issue by Pant** [husisusi/officeonlin-install.sh#205]
Hi.

I just wanted to let you know i managed to build a docker image based on this repository. Here it is: 

https://hub.docker.com/repository/docker/pant/collabora-online

Use it at your own risk 

Thank you very much :)

**Comment by ZainulSaifulah** [comment]
Hi @Pant, can you share your dockerfile and other configuration went you build your docker image ? it will be nice for me. I was try to build docker image for libreoffice with my configuration several time but it still error. Thank you

**Comment by ryukenji3** [comment]
Hi @Pant , thanks for your docker image and it's excellent. Just wondering whether you clean up unnecessary files generated during the compilation to make the size of this image more reasonable.

Now the image size after exporting with the docker save command is similar to that of a complete virtual machine, extremely slow while pulling from docker hub. Thank you.

**Comment by ryukenji3** [comment]
Advice: It seems that no locale set in the docker base image,  someone may encounter "Please ensure the file type is supported and not corrupted" error when open file which name is not in English, such as Russian/Japanese/Chinese file name.


 #It may occur that no locales are set on systems.Furthermore, the **locale -a** command returns following:

```
 C
 C.UTF-8
 POSIX
```

```
#Generate locale
sudo locale-gen en_US.UTF-8
#Set locale, this generates also the /etc/default/locale file.
update-locale LANG=en_US.UTF-8
```
