### ISSUE TITLE
Style sidebar

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#208]
In the last version compiled (05-22-2020), when you open a document, you have the style sidebar opened by default.

Does anyone know if it's possible to have it hidden by default?

Thanks

```
lo_src_branch='distro/collabora/cp-6.2'
lo_src_tag='cp-6.2-11' 
poco_version=1.9.4 
lool_src_branch='distro/collabora/co-4-2-3'
lool_src_tag='CODE-4.2.3-1' 
```

**Comment by titansmc** [comment]
the same for me, would be nice to have it disabled.

**Comment by DmDS** [comment]
https://github.com/husisusi/officeonlin-install.sh/issues/188#issuecomment-725619985
