### ISSUE TITLE
configure: error: unrecognized options: --disable-gstreamer-0-10, --disable-kde4

### ISSUE THREAD

**Issue by hellkaim** [husisusi/officeonlin-install.sh#209]
Hi,
am trying to build the suit on Ubuntu 18.04. 

After solving dependency problems got the following
`Running ./configure with '--disable-dbus --disable-dconf --disable-epm --disable-ext-nlpsolver --disable-ext-wiki-publisher --disable-gio --disable-gstreamer-0-10 --disable-gstreamer-1-0 --disable-gtk3 --disable-kde4 --disable-odk --disable-online-update --disable-postgresql-sdbc --disable-report-builder --disable-scripting-beanshell --disable-sdremote --disable-sdremote-bluetooth --enable-mergelibs --enable-python=internal --with-external-dict-dir=/usr/share/hunspell --with-external-thes-dir=/usr/share/mythes --with-galleries=no --with-lang= --with-linker-hash-style=both --with-system-dicts --without-branding --without-help --without-java --without-myspell-dicts --without-package-format --without-system-jars --without-system-libpng --without-system-libxml --without-system-poppler --without-system-postgresql --srcdir=/opt/libreoffice --enable-option-checking=fatal'
configure: error: unrecognized options: --disable-gstreamer-0-10, --disable-kde4
Error running configure at ./autogen.sh line 309.
`

**Comment by GrifKies** [comment]
Me too

**Comment by GrifKies** [comment]
the directory for the script autogen.sh is **/opt/libreoffice**. The main issue that I have found is with the Collabora version/distro (LibreOfficeOnline). They must have updated there configure script params since the general libreoffice script was written.

**Comment by GrifKies** [comment]
Try editing the 

> Hi,
> am trying to build the suit on Ubuntu 18.04.
> 
> After solving dependency problems got the following
> `Running ./configure with '--disable-dbus --disable-dconf --disable-epm --disable-ext-nlpsolver --disable-ext-wiki-publisher --disable-gio --disable-gstreamer-0-10 --disable-gstreamer-1-0 --disable-gtk3 --disable-kde4 --disable-odk --disable-online-update --disable-postgresql-sdbc --disable-report-builder --disable-scripting-beanshell --disable-sdremote --disable-sdremote-bluetooth --enable-mergelibs --enable-python=internal --with-external-dict-dir=/usr/share/hunspell --with-external-thes-dir=/usr/share/mythes --with-galleries=no --with-lang= --with-linker-hash-style=both --with-system-dicts --without-branding --without-help --without-java --without-myspell-dicts --without-package-format --without-system-jars --without-system-libpng --without-system-libxml --without-system-poppler --without-system-postgresql --srcdir=/opt/libreoffice --enable-option-checking=fatal' configure: error: unrecognized options: --disable-gstreamer-0-10, --disable-kde4 Error running configure at ./autogen.sh line 309. `

Try going to /opt/libreoffice/distro-configs/LibreOfficeOnline.conf, and removing the problem params. you might have to copy this file, and specify it as the distro.

**Comment by hellkaim** [comment]
`Try going to /opt/libreoffice/distro-configs/LibreOfficeOnline.conf, and removing the problem params. you might have to copy this file, and specify it as the distro.`

That was exactly what I did. Just thought it might be worth mentioning. Compiling on Ubuntu 18.04.4
After that and some other issues with llibraries compilation went fine and I was able to use the DocumentServer.

**Comment by sukarechhe** [comment]
Modified -> LibreOfficeOnline.conf but still having same issue. can someone please shade some lights on this ?
