### ISSUE TITLE
Some partition tips ?

### ISSUE THREAD

**Issue by Yamakasi** [husisusi/officeonlin-install.sh#21]
Hi,

This script is great, but is it ideal to have some partition tips so your system won't fill up partitions while compiling ?

Would be nice to know!

Thanks

**Comment by husisusi** [comment]
Hello  Yamakasi,
the most important thing to have => 16 GB free space on opt.

**Comment by Yamakasi** [comment]
OK, thanks, I started with 12GB there, but as I don't use /home on that
machine and lool is cached there it's 100% filled while compiling. Doesn't
matter for the compile but it's just something to mention.

2017-03-22 22:21 GMT+01:00 husisusi <notifications@github.com>:
