### ISSUE TITLE
Collaboration in document bug?

### ISSUE THREAD

**Issue by mpochopien** [husisusi/officeonlin-install.sh#211]
Hi all,

first, I've managed to successfully install LOO on Ubuntu 18.04. It works just fine with NC. Now, I've encountered a bug with collaboration on the document at the same time. When two users try to work on the same document simultaneously, one of the users can't use a sidebar. Moreover, that user controls the sidebar of another user. Is it a bug or some config mistake on my side?

Thanks for your help.

**Comment by husisusi** [comment]
Actually no, please try the last version and update your NC.
