### ISSUE TITLE
openjdk-8-jdk : unknown command

### ISSUE THREAD

**Issue by ClCfe** [husisusi/officeonlin-install.sh#212]
Hello

I think you have an extraneous line break here
https://github.com/husisusi/officeonlin-install.sh/blob/5c96300fa4cd562dfb50904d102d20f97624171c/bin/systemSetup.sh#L76-L78

/opt/ooinstaller/bin/systemSetup.sh: ligne 78: openjdk-8-jdk : unknown command

**Comment by husisusi** [comment]
@ClCfe Fixed. Thanks!
