### ISSUE TITLE
Build process on Ubuntu 18.04 not working

### ISSUE THREAD

**Issue by FJCF76** [husisusi/officeonlin-install.sh#215]
Hello, 

Thanks for the effort of maintaining a build script for lool.
I did exactly this on a fresh Ubuntu 18.04 VPS:

apt-get update && sudo apt-get --with-new-pkgs upgrade
apt autoremove
reboot
sudo dpkg-reconfigure tzdata (to set my timezone)
git clone https://github.com/husisusi/officeonlin-install.sh.git
cd officeonlin-install.sh/
nano officeonline-install.cfg
allowed_domains="domain1.com domain2.com"
lool_maxcon=200
lool_maxdoc=200
./officeonline-install.sh

After that (and many hours of the build process running) I get (with a few OK lines before the error):
WhiteBoxTests::testRectanglesIntersect. : OK
WhiteBoxTests::testAuthorization. : OK
WhiteBoxTests::testJson. : OK
WhiteBoxTests::testAnonymization. : OK
DeltaTests::testDeltaSequence. : OK
DeltaTests::testRandomDeltas. : OK

OK (25)
make[2]: Leaving directory '/opt/online/test'
Making all in loleaflet
make[2]: Entering directory '/opt/online/loleaflet'
/opt/online/scripts/unocommands.py --check /opt/online
make[3]: Entering directory '/opt/online/loleaflet'
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/browser-resolve/node_shrinkwrap/resolve-1.1.7.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/concat-stream/node_shrinkwrap/process-nextick-args-1.0.7.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/concat-stream/node_shrinkwrap/readable-stream-2.0.6.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/globby/node_shrinkwrap/glob-7.1.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/randomatic/node_shrinkwrap/is-number-4.0.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/randomatic/node_shrinkwrap/kind-of-6.0.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/rimraf/node_shrinkwrap/glob-7.1.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/acorn-jsx/node_shrinkwrap/acorn-3.3.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/uglifyify/node_shrinkwrap/minimatch-2.0.10.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/acorn-node/node_shrinkwrap/acorn-5.5.3.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/url/node_shrinkwrap/punycode-1.3.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/yargs/node_shrinkwrap/wordwrap-0.0.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/espree/node_shrinkwrap/acorn-5.5.3.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/css-stringify/node_shrinkwrap/source-map-0.1.43.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/labeled-stream-splicer/node_shrinkwrap/isarray-2.0.4.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/util/node_shrinkwrap/inherits-2.0.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/exorcist/node_shrinkwrap/minimist-0.0.5.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/mold-source-map/node_shrinkwrap/through-2.2.7.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/mkdirp/node_shrinkwrap/minimist-0.0.8.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/inquirer/node_shrinkwrap/lodash-4.17.10.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/readable-stream/node_shrinkwrap/string_decoder-1.1.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/uglify-js/node_shrinkwrap/source-map-0.1.34.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/detective/node_shrinkwrap/acorn-5.5.3.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/shrinkpack/node_shrinkwrap/commander-2.9.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/shrinkpack/node_shrinkwrap/glob-7.0.5.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/shrinkpack/node_shrinkwrap/graceful-fs-4.1.4.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/insert-module-globals/node_shrinkwrap/concat-stream-1.6.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/table/node_shrinkwrap/ansi-regex-3.0.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/table/node_shrinkwrap/is-fullwidth-code-point-2.0.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/table/node_shrinkwrap/lodash-4.17.10.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/table/node_shrinkwrap/string-width-2.1.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/table/node_shrinkwrap/strip-ansi-4.0.0.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/browserify-css/node_shrinkwrap/concat-stream-1.4.11.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/browserify-css/node_shrinkwrap/isarray-0.0.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/browserify-css/node_shrinkwrap/readable-stream-1.1.14.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/browserify-css/node_shrinkwrap/through2-0.6.5.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/ajv/node_shrinkwrap/json-stable-stringify-1.0.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/select2/node_shrinkwrap/jquery-mousewheel-3.1.13.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/eslint/node_shrinkwrap/glob-7.1.2.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/eslint/node_shrinkwrap/json-stable-stringify-1.0.1.tgz
npm ERR! addLocal Could not install /opt/online/loleaflet/node_modules/eslint/node_shrinkwrap/lodash-4.17.10.tgz
npm ERR! Linux 4.15.0-143-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /opt/online/loleaflet/node_modules/browser-resolve/node_shrinkwrap/resolve-1.1.7.tgz
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/opt/online/loleaflet/node_modules/browser-resolve/node_shrinkwrap/resolve-1.1.7.tgz'
npm ERR! enoent ENOENT: no such file or directory, open '/opt/online/loleaflet/node_modules/browser-resolve/node_shrinkwrap/resolve-1.1.7.tgz'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/online/loleaflet/npm-debug.log
make[3]: *** [node_modules] Error 254
Makefile:726: recipe for target 'node_modules' failed
make[3]: Leaving directory '/opt/online/loleaflet'
Makefile:612: recipe for target 'all-local' failed
make[2]: Leaving directory '/opt/online/loleaflet'
make[2]: *** [all-local] Error 2
Makefile:1983: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/online'
make: *** [all] Error 2
Makefile:878: recipe for target 'all' failed
make: Leaving directory '/opt/online'

Any idea what is happening?

Thanks!

**Comment by FJCF76** [comment]
Hello, 

It would really help if someone could provide some guidance about this error.

Thanks!

**Comment by joergmschulz** [comment]
maybe you need to follow https://wiki.documentfoundation.org/Development/BuildingOnline and look for the headline 

Prerequisites for building on Ubuntu 18.04

at least this is what helped me building on an Ubuntu system. Else switch to Debian.

**Comment by FJCF76** [comment]
Great. Thanks!

**Comment by FJCF76** [comment]
Hello,

I tried many times, including the requirements for ubuntu listed in  https://wiki.documentfoundation.org/Development/BuildingOnline, but I can't find a way around that error. It always fails exactly at that point.

Would you have any other idea of what could I explore or try? Switching to Debian is not an option to me.

Thanks!

**Comment by quenenni** [comment]
Can you tell me the npm and node  version you have installed on your server?

Also, did you try to test your npm manually (outside the Lool script).
I see here users that have the same error:
https://github.com/npm/npm/issues/11385
