### ISSUE TITLE
Debian 11

### ISSUE THREAD

**Issue by DmDS** [husisusi/officeonlin-install.sh#216]
to compile on debian 11, you need to edit the script.

```
../bin/
onlinePrep.sh
systemSetup.sh
```

search for 'buster' and edit the strings

before
  `if [ "${CODENAME}" = "Buster" ];then`

after
  `if [ "${CODENAME}" = "Buster" ] || [ "${CODENAME}" = "bullseye" ];then`

**Comment by husisusi** [comment]
> to compile on debian 11, you need to edit the script.
> 
> ```
> ../bin/
> onlinePrep.sh
> systemSetup.sh
> ```
> 
> search for 'buster' and edit the strings
> 
> before
> `if [ "${CODENAME}" = "Buster" ];then`
> 
> after
> `if [ "${CODENAME}" = "Buster" ] || [ "${CODENAME}" = "bullseye" ];then`

Thank you!
can you please create pull request?

**Comment by DmDS** [comment]
> can you please create pull request?

done

**Comment by husisusi** [comment]
Thanks DmDS!
