### ISSUE TITLE
download as pdf not working

### ISSUE THREAD

**Issue by quenenni** [husisusi/officeonlin-install.sh#221]
When choosing in the File menu "Download as" -> PDF document, I have a popup window with the msg:
`Document can not be exported. Please contact the storage server administrator`

All other options in "Download as" submenu are working fine.

The logs on the server are showing this:
```
Apr 15 18:57:29 cool coolwsd[1508504]: kit-1508504-1508242 2022-04-15 20:57:29.219598 +0200 [ kitbroker_008 ] ERR  SaveAs Failed for id=export [/tmp/user/docs/eFfhPkN0yngVP03q9Oi3A474yOOXnCDaRGdBddvAUTNTivtNfuNjfV4uGGLpRCq0/Nouveau%20Docu
ment.pdf]. error= exception: SfxBaseModel::impl_store <file:///tmp/user/docs/eFfhPkN0yngVP03q9Oi3A474yOOXnCDaRGdBddvAUTNTivtNfuNjfV4uGGLpRCq0/Nouveau%20Document.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) /opt/libreoffice1/sfx2/
source/doc/sfxbasemodel.cxx:3153 /opt/libreoffice1/sfx2/source/doc/sfxbasemodel.cxx:1735| kit/ChildSession.cpp:1076
Apr 15 18:57:29 cool coolwsd[1508504]: kit-1508504-1508242 2022-04-15 20:57:29.219699 +0200 [ kitbroker_008 ] ERR  error: cmd=downloadas kind=saveasfailed| ./common/Session.hpp:139
Apr 15 18:57:29 cool coolwsd[1508235]: wsd-1508235-1508529 2022-04-15 20:57:29.219818 +0200 [ docbroker_008 ] ERR  downloadas error failure: saveasfailed| wsd/ClientSession.cpp:1489
```

Is it a problem in Cool or maybe I need to install packages to enable this?

**Comment by husisusi** [comment]
I cannot reproduce this issue.
Try to install libgs9 libgs9-common ghostscript imagemagick

**Comment by quenenni** [comment]
@husisusi Thanks for the help.

All these packages are already installed.

**Comment by tm-berlin** [comment]
> When choosing in the File menu "Download as" -> PDF document, I have a popup window with the msg: `Document can not be exported. Please contact the storage server administrator`
> 
> All other options in "Download as" submenu are working fine.
> 
> The logs on the server are showing this:
> 
> ```
> Apr 15 18:57:29 cool coolwsd[1508504]: kit-1508504-1508242 2022-04-15 20:57:29.219598 +0200 [ kitbroker_008 ] ERR  SaveAs Failed for id=export [/tmp/user/docs/eFfhPkN0yngVP03q9Oi3A474yOOXnCDaRGdBddvAUTNTivtNfuNjfV4uGGLpRCq0/Nouveau%20Docu
> ment.pdf]. error= exception: SfxBaseModel::impl_store <file:///tmp/user/docs/eFfhPkN0yngVP03q9Oi3A474yOOXnCDaRGdBddvAUTNTivtNfuNjfV4uGGLpRCq0/Nouveau%20Document.pdf> failed: 0xc10(Error Area:Io Class:Write Code:16) /opt/libreoffice1/sfx2/
> source/doc/sfxbasemodel.cxx:3153 /opt/libreoffice1/sfx2/source/doc/sfxbasemodel.cxx:1735| kit/ChildSession.cpp:1076
> Apr 15 18:57:29 cool coolwsd[1508504]: kit-1508504-1508242 2022-04-15 20:57:29.219699 +0200 [ kitbroker_008 ] ERR  error: cmd=downloadas kind=saveasfailed| ./common/Session.hpp:139
> Apr 15 18:57:29 cool coolwsd[1508235]: wsd-1508235-1508529 2022-04-15 20:57:29.219818 +0200 [ docbroker_008 ] ERR  downloadas error failure: saveasfailed| wsd/ClientSession.cpp:1489
> ```
> 
> Is it a problem in Cool or maybe I need to install packages to enable this?

Same for me. libgs9 libgs9-common ghostscript imagemagick installed. Neither in Debian 10 nor in Ubuntu 20.04.
I have no idea where to look.

**Comment by DmDS** [comment]
COOLWSD: 23.05.2.2
LOKit: Collabora Office 23.05.2.3
Debian 12, Ubuntu 22.04

exporting to PDF works.
