### ISSUE TITLE
SSL Exception [in file "src/ErrorHandler.cpp", line 40]

### ISSUE THREAD

**Issue by Yamakasi** [husisusi/officeonlin-install.sh#25]
This is what I get on my LibreOffice Online server when I access a file and get Access Denied:

Mar 23 00:23:12 ofco-01 loolwsd[1656]: SSL Exception [in file "src/ErrorHandler.cpp", line 40]
Mar 23 00:23:12 ofco-01 loolwsd[1656]: %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

I use https://fqdnOfLIbreOfficeServer:8890 in my collabora settings.

I have already copied in the /etc/loolwsd/cert.pem to /var/www/nextcloud/resources/config/ca-bundle.crt

**Comment by aalaesar** [comment]
Hi,
this does'nt say much
all I can say is that src/ErrorHandler.cpp is a poco file 😕
do you have a little bit more logs ?
This could be a problem with nextcloud's cert
do you use self-signed certificate for both lool and nextcloud ?

**Comment by Yamakasi** [comment]
Hi,

I don't see any more logs, at least not on the lool side, this is what comes out.

The Nexcloud install uses as signed cert and the lool uses a self-signed cert as generated during your build.

Can I higher up logs, do I check wrong logs ? This came from journalctl -f

**Comment by aalaesar** [comment]
full lool debug logs are in /var/log/loolwsd.log in you run the script v2.0 or in /tmp/loolwsd.log for earlier version.
However, it seems that your issue is fixed on the forum ?

**Comment by Yamakasi** [comment]
Yes seems so :) thanks!
