### ISSUE TITLE
Libreoffice compile failed

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#29]
I have a partition of 26 GB for /opt/
My version of Libreoffice was 5.3.1.1
The script tries to compile 5.3.1.2 but my disk is 100% full after a while. It seems that 5.3.1.1 is left in place where it probably should be deleted.

**Comment by Kassiematis** [comment]
My fault, different issue.

**Comment by aalaesar** [comment]
Anyway, I just realised, thanks to your issue, that the check available space fails its purpose in the case of updating LibreOffice
1. the script test OK that LO exists and ignore the space requirement of 11GB
2. Later it founds that current version is not the desired, then proceed to rename the current LO folder and compile the desired one, leading potentially to disk space issues.

**Comment by Kassiematis** [comment]
I removed libreoffice dirs and compile works fine.
