### ISSUE TITLE
Feature: configure Loowsd through loolwsd.xml instead of command line arguments

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#31]
----
This is a opened discussion thread about a potential feature.

----
# Feature: Loolwsd enriched post-install configuration.
## Context
Loolwsd use a conf file in xml format to define how it work, log and accept connections
Some of theses parameters are configured as default in the XML by the `./configure` script using options. like `--with-logfile`:
```XML
<property name="path" desc="Log file path.">/var/log/loolwsd.log</property>
```
However there are much more configuration options inside the file that are not covered  by the `configure` script's options
the [file](https://github.com/LibreOffice/online/blob/master/loolwsd.xml.in) is thankfully self-describing the parameters.
Actually mandatory parameters for loolwsd are given CLI style but do not cover some essential need like adding allowed wopi hosts.
## Suggestions
Would be a big plus to switch from CLI configuration to loolwsd.xml.
there's a lot of ways this could be possible.
- [ ] using a optional response file for setting the parameters
- [ ] using a template for the xml file
- [ ] using more paramaters in the script
- [ ] ... suggest more !!

**Comment by Kassiematis** [comment]
Adding wopi hosts would be helpful and I always have to disable "trace desc" because for some reason it does not work for me.

**Comment by aalaesar** [comment]
Hi, Quick update:
Still working on it when I have some time.
I'll make it in python for parsing and generating the XML conf file in an idempotent way
Regards.

**Comment by aalaesar** [comment]
Small update ; for now I'm looking into implementing a single feature that just adds allowed wopi hosts in the loolwsd.xml as post-install.
