### ISSUE TITLE
tests: recheck LO space requirements

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#33]
I was testing the script for the last PR when I noted a big difference in disk usage of LibreOffice folder than noted in the readme and previously checked. 
```shell
root@debian:/opt# du -sh *
2.7G    libreoffice
2.7G    libreoffice-5.3.1.0 # fake version number 5.3.1.2
181M    libreoffice-5.3.1.2.tar.xz
2.7G    libreoffice-old
604M    online
```
Here I Tried of overload the disk usage by copying multiple time the libreoffice folder. It was supposed to use about 12GB last time I mesured it.
but here It uses *only* 2.7 GiB. 😕 
This doesn't mean that LO compilation won't use more than 2.7 GiB during compilation, however, I want to known from various users how much space LO uses on their setup.

**Comment by Kassiematis** [comment]
lool homedir has a .ccache folder with 5G of data because of compiling.
use `du -sch .[!.]* * | sort -h` in the homedir to see how much is used.
Libreoffice = 2.6G
Poco = 528M
online = 613M

**Comment by Kassiematis** [comment]
While compiling i have the following disk usage for Libreoffice
Libreoffice 2.6G
/opt/libreoffice/Workdir before being deleted 6.4G
/home/lool/.ccache 5G

Total 14GB

**Comment by sergey-dryabzhinsky** [comment]
Even without ccache LiO build may take up to 8Gb in some moments.

**Comment by husisusi** [comment]
Can I close thus issue?
