### ISSUE TITLE
Improvement: reduce LibreOffice to its minimum for Online use

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#34]
----
This is a opened discussion about a improvement of a script's function

----
## Context
Actual LO (LibreOffice) compilation is configured following recommended options for general purpose. However there's a lot of modules that are not required/used *yet* by the online websocket but that are still compiled , therefore taking useless cpu time during installation.
## Suggestion
 Make an optional "minimal LO build trigger" to change the compilation options for LO and still having a fully functional Online service.
This is the easy part,

The hardest part is to find the `./configure` options along with the `make `options 
for now I have some leads [here ](https://wiki.documentfoundation.org/Development/BuildingOnLinux), [here ](https://wiki.documentfoundation.org/Development/ReleaseBuilds#Linux_.28same_options_for_x86_.26_x86_64.29) and [here](https://wiki.documentfoundation.org/Development/GenericBuildingHints)

## request
Is here someone with more knowledge/experience in tuning LibreOffice build or a C++ project in general that could help ?

**Comment by sergey-dryabzhinsky** [comment]
Totally agree.

My suggestions:

At first look there is some safe options to disable features not needed by headless service:
- --disable-avmedia
- --disable-database-connectivity
- --disable-lpsolve
- --disable-coinmp
- --disable-gtk
- --disable-gtk3
- --disable-systray
- --disable-dbus
- --disable-gui
- --disable-randr
- --disable-gstreamer-1-0
- --without-helppack-integration

And enable some optimizations (may build longer):
- --enable-lto
- --enable-eot
- --enable-release-build
- --with-system-bzip2
- --with-system-zlib
- --with-system-jpeg
- --with-system-expat
- --with-system-libxml
- --with-system-icu
- --with-system-poppler
- --with-system-curl
- --with-system-boost
- --with-system-libpng
- --with-alloc=jemalloc (need libjemalloc-dev)

There is may be more options. Can look into Ubuntu/Debian LibreOffice source package.

**Comment by sergey-dryabzhinsky** [comment]
Questionable options:
- --enable-python=no - do LooL need python?
- --disable-neon - do we need webdav here?
- --disable-cups - do we need printing here?
- --disable-gltf --disable-collada - need some 3d modeling import?
- --enable-introspection=no - not sure about this
- --disable-pdfimport - how often people import pdf into Draw?
- --disable-odk - ODK probably not needed
- --disable-extension-update - this probably not needed too
- --without-java - JAVA probably not needed

**Comment by sergey-dryabzhinsky** [comment]
So, not all go well.
I'll update working set of options soon.

**Comment by aalaesar** [comment]
Thank you @sergey, 👍
Do you know if it possible to build only some modules instead of all the project ? Like core, writer, table and draw ?

**Comment by sergey-dryabzhinsky** [comment]
I think not.
It's even not possible build LiO without GUI, OpenGL, DB drivers, other strange stuff.

At least we can reduce build time by using some system libraries.
And disable python, java, and small amount of other stuff.

**Comment by aalaesar** [comment]
OK Thanks 
I supposed it could be possible while reading the LiO's [ github Readme](https://github.com/LibreOffice/core/blob/master/README.md) for they took the time to writes about what module are importants.
maybe we need to simply run the "make" from inside the module's folder... 😕

**Comment by sergey-dryabzhinsky** [comment]
Once I was tried to build python-uno separately. No luck.

**Comment by sergey-dryabzhinsky** [comment]
And something strange happens with systemd unit:
- loolwsd can't make forks after some time,
- systemd looses cgroup it maked for loolwsd

May be it's because I using OpenVZ + 2.6.32 (Proxmox 3.4). It may have no complete support for cgroups.
I'll try KVM with fresh Debian 8.7 soon.

**Comment by Kassiematis** [comment]
I have been testing disabling different functionality with compiling and this is what i came up with. With-system-XXXX options gave varying results so I left them out. Compile with 3 cpu was done in less than 2 hours.

--without-help
--without-myspell-dicts
--without-java 
--without-doxygen 
--disable-cups 
--disable-dconf 
--disable-odk 
--without-junit 
--disable-dbus 
--disable-firebird-sdbc 
--disable-postgresql-sdbc
--disable-gltf 
--disable-extensions 
--disable-pdfimport 
--disable-neon

**Comment by Kassiematis** [comment]
Some more options to disable.
--disable-lpsolve
--disable-coinmp
--disable-systray
--disable-randr
--disable-gstreamer-1-0
--without-helppack-integration
--disable-report-builder 
--disable-coinmp 
--disable-pdfium 
--disable-collada

**Comment by quenenni** [comment]
Very nice idea. 
Where exactly do I have to put these params? 
In the 'lo_configure_opts' var?

**Comment by Kassiematis** [comment]
I have created a pull request so it is already in the script.
#106

**Comment by quenenni** [comment]
Very nice. Thanks. Without knowing it, I downloaded the last version just after your pull.

**Comment by aalaesar** [comment]
update:
I've been using the options found in this file : https://github.com/LibreOffice/online/blob/distro/collabora/collabora-online-3-0/docker/l10n-docker-nightly.sh for Libreoffice build (except the disable cups) and result have been quite goods building from scratch.
I'll look for pushing them as default.
