### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#36]
./officeonline-install.sh: line 206: [: too many arguments

**Comment by aalaesar** [comment]
Hi, 
can you try to rerun the script with `set -x` added at line 2
then report the log file present in  /tmp/
thanks.

**Comment by Kassiematis** [comment]
Uploaded

[20170403-1256_officeonline.zip](https://github.com/husisusi/officeonlin-install.sh/files/889797/20170403-1256_officeonline.zip)

**Comment by Kassiematis** [comment]
This is probably the problem

grep PACKAGE_VERSION= /opt/libreoffice/configure
PACKAGE_VERSION='5.3.2.1'
PACKAGE_VERSION="$with_package_version"

I am using the testing version of libreoffice

**Comment by aalaesar** [comment]
Yes obviously
but that's weird, looks like a mess-up with the configuration step
from my test setup I get this 
```shell
root@debian:/opt/libreoffice# grep PACKAGE_VERSION= configure
PACKAGE_VERSION='5.3.1.2'
```

> I am using the testing version of libreoffice

Ho, ok. could be that

how about test `grep PACKAGE_VERSION=\' /opt/libreoffice/configure` ?
should work

**Comment by Kassiematis** [comment]
This is what i came up with
grep PACKAGE_VERSION= /opt/libreoffice/configure | cut -d \' -f 2 | head -1

**Comment by Kassiematis** [comment]
Even better

`grep PACKAGE_VERSION=\' /opt/libreoffice/configure | cut -d \' -f 2 | head -1`

**Comment by Kassiematis** [comment]
I tested it and its working.
