### ISSUE TITLE
Debian: directory for loolwsd.service is /etc/systemd/system

### ISSUE THREAD

**Issue by joergmschulz** [husisusi/officeonlin-install.sh#42]
Some minutes ago, the compilation succeeded - but as I had an old loolwsd.service in the correct directory /etc/systemd/system, it didn't start.
So, this remark:
`loolwsd.service` must be installed in `/etc/systemd/system`.
Afterwards 
`systemctl daemon-reload` 
has to be started, then everything works perfect.

**Comment by Kassiematis** [comment]
Will this fix the problem?

https://github.com/Kassiematis/officeonlin-install.sh/commit/9cdfeb6e1b849946659bcd55adce0820fa79e4fd
