### ISSUE TITLE
Old Libreoffice folder not moved to /opt

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#44]
For some reason the script places the old libreoffice in the folder the script is started from.

```
 check is libreoffice sources are already present and in the correct version 
if [ -d ${lo_dir} ]; then 
lo_local_version="libreoffice-$(grep 'PACKAGE_VERSION=' ${lo_dir}/configure | cut -d \' -f 2)" 
 rename the folder if not in the expected verion 
[ ${lo_local_version} != ${lo_version} ] && mv ${lo_dir} ${lo_local_version} 
fi 
```

Will this work?

`[ ${lo_local_version} != ${lo_version} ] && mv ${lo_dir} /opt/${lo_local_version}`

**Comment by aalaesar** [comment]
Hi, thank you for pointing this issue 
We can use `$(dirname ${lo_dir})` instead of /opt to avoid hard-coded directory. 🙂

**Comment by Kassiematis** [comment]
Something like this?

`[ ${lo_local_version} != ${lo_version} ] && mv ${lo_dir} $(dirname ${lo_dir})/${lo_local_version}`
