### ISSUE TITLE
Git commit version

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#49]
Git shows with lool the latest master as the version from https://github.com/husisusi/online
How can I change that to https://github.com/LibreOffice/online?

**Comment by aalaesar** [comment]
Hi,
Latest version of the script should use the official github repo for lool.
[See here](https://github.com/husisusi/officeonlin-install.sh#sources-status) in the doc. 😄
Regards,
Aal.

**Comment by Kassiematis** [comment]
The script does use the official repo but because the old script used a different repo in the beginning my local repo is different.

The command `git rev-parse HEAD` shows 1c3eca6d4e944a718da67567cb5f2b6d90b9d5a0
This commit is the last version from https://github.com/husisusi/online

**Comment by aalaesar** [comment]
Ok, in this case you need to remove the actual repo and rerun the script.

**Comment by Kassiematis** [comment]
I did with command rm -r .git
Now my owncloud server cannot connect anymore after a new compile.

`/opt/online/loleaflet/1c3eca6/loleflet.html does not exist.`

1c3eca6 seems to reference to the old repo.

**Comment by aalaesar** [comment]
I think the script did'nt recompiled loolwsd because it's looking for the folder /opt/online to clone (if absent) & configure the repository and the presence/absence of '/opt/online/loolwsd' to decide to run the compilation (unless you use lool_forcebuild=true)
I suggest you remove/rename '/opt/online' and rerun the script. 😄

**Comment by aalaesar** [comment]
NB : Please, leave this issue open , i'll add code to verify the repository source is the same as the parameters.

**Comment by Kassiematis** [comment]
I have it working again with removing /opt/online after first running `make clean uninstall`

**Comment by Kassiematis** [comment]
/home/lool/.ccache has to be cleared as well
