### ISSUE TITLE
tests: recheck memory requirements for x64 host

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [husisusi/officeonlin-install.sh#55]
To build LiO on amd64 Debian 8 machine we need more than 6Gb memory.

**Comment by aalaesar** [comment]
Hi @sergey,
What happen if there is less than 6GB ? Drop in performances ?
Actually, my tests are run on a debian 8 amd64 vhost with 4GB of ram.

**Comment by sergey-dryabzhinsky** [comment]
My build just breaks with "Killed" and "oops" in syslog.

May be it is because --enable-lto configure option.
LTO can be memory eater.

**Comment by sergey-dryabzhinsky** [comment]
My build killed on CVE tests.
So I disabled them.

**Comment by aalaesar** [comment]
So did it fixed it ?
what was the option in ./configure ?

**Comment by sergey-dryabzhinsky** [comment]
I'm checking that right now. Still compiling.
As for option it was `--disable-cve-tests`.

**Comment by sergey-dryabzhinsky** [comment]
Nope. 4G not enough to build with LTO.
I'll try again without `--enable-lto`.

**Comment by sergey-dryabzhinsky** [comment]
Yes, 4Gb enough to build W/O LTO.

So if you will not use `--enable-lto` configure option then 4Gb will be alright.

**Comment by aalaesar** [comment]
Does LTO stand for "Linear Tape-Open" ?

**Comment by sergey-dryabzhinsky** [comment]
Nope, it's Link Time Optimization: https://gcc.gnu.org/wiki/LinkTimeOptimization

**Comment by aalaesar** [comment]
Ok thank you 😄 👍

**Comment by sergey-dryabzhinsky** [comment]
No issue here. Closing.
