### ISSUE TITLE
[Suggestion] - Split the script into multiple files.

### ISSUE THREAD

**Issue by aalaesar** [husisusi/officeonlin-install.sh#60]
Hi there,
since the script started to grow both in size and in contribution, 
the idea of splitting the script's code into multiples sub script or modules have grown bigger every day to myself.
The big idea whould be to Have 1 main script calling all the other ones. Each sub-script would contains one **idempotent** feature.
I see mostly advantages into doing so:
- Simpler scripts, easier to read instead of a big files of 500 lines (and increasing)
- easier contributions: don't want to rebase all the time your branch and deal with merge conflicts when working on a fix/feature ? We need more than 1 file 😉 ! 
- easier support: come with the previous point in fact...
- More languages ! In fact bash have some limitation that some other language like perl/python could solve.

However, this would add complexity to the repo and may requires to "level-up" the contributions standards like:
- A contribution must be idempotent or must not break idempotence
- a script should be (self)documented
- use [standard return code](http://www.tldp.org/LDP/abs/html/exitcodes.html)
- use [stdout and stderr correctly](http://tldp.org/HOWTO/Bash-Prog-Intro-HOWTO-3.html)

This would be hard work first but would Really paid off in the long run
What do you think ?

**Comment by aalaesar** [comment]
Here's an example
(don't bother about the naming convention, its just testing)

![image](https://cloud.githubusercontent.com/assets/18649249/25073688/080a9b50-22ec-11e7-839b-05ca623810a1.png)

test branch [here](https://github.com/aalaesar/officeonlin-install.sh/tree/Split_script)

**Comment by Kassiematis** [comment]
Looks good, if in the future there will be a lot changes it will make sense. The script is quite mature now and I don't think there will be a lot off changes anymore.

**Comment by husisusi** [comment]
Strongly agree with @Kassiematis. It will make sense just  if in the future there will be a lot of changes.
I am working on deb package (just for lo) and it works on Ubuntu. The package is 680 MB and the lo installation take 3-4 min. Debian installation remained broken...
The problem, where to store 680 MB deb package?

**Comment by Ark74** [comment]
If you need something like a ftp space i could help.
I have some room to host it.

**Comment by aalaesar** [comment]
Hi @Kassiematis , @husisusi, You're totally right.  That's why I made this suggestion:
Even if i'm not very present since 2 weeks (less avail time until mid july), i'm following most of the PR and issues posted.
I get the feeling that most of the contributors are wishing to improve the script further on some points:
- size&time optimization
- packaging
- integration/installation.
- add more features (configuration from files etc)

I also think some of us plan to get something more than a script, something usable by _continuous delivery_ pipes.

From my perspective, I think the script is good, but not ready for production
it's becoming big and harder to maintain.

**=>The repository will be more improved by various contributors (at least by me :p ) in the future, So we will gain in time and management if it is split before.**

---------------
> I am working on deb package (just for lo) and it works on Ubuntu.

Those are sweet words to me :p , I want to know more if you wish to share.

> The problem, where to store 680 MB deb package?

**Nowhere** special I think, or in `/opt` to be more specific.
IF you plan to add this function to the script, the package will be either used by the script or left to the user's will. The script creates the environment and the service , but not a deb repo, that would leave its first purpose.
Anyway, this would be a very good improvement ! 👍

**Comment by husisusi** [comment]
@Ark74 ftp space will be great.

**Comment by Ark74** [comment]
@husisusi how should  i contact you for details?

**Comment by husisusi** [comment]
@Ark74 : you can send me e-Mail
Ark74 at ...

**Comment by Ark74** [comment]
Let me know if you get the message i just sent.

**Comment by enoch85** [comment]
This is how it's done in the [Nextcloud VM](https://github.com/nextcloud/vm) and it gives a better structure.

**Comment by aalaesar** [comment]
working on it
[here's a working version](https://github.com/aalaesar/officeonlin-install.sh/tree/Split_script) with a bonus: a config file dedicated for users.
further testing would be appreciated 😃
