### ISSUE TITLE
Pin versions

### ISSUE THREAD

**Issue by Gomez** [husisusi/officeonlin-install.sh#63]
I tested the script and noticed it uses master on most of the versions. 

I want to build a server with a know-good-state and make it reproduce-able. AFAIK this is only possible, i need to edit "officeonlin-install.sh" and add the version numbers. 

Would it be a good idea to use parameter expansion for the version vars, like this:

http://stackoverflow.com/questions/4609668/override-variable-in-bash-script-from-command-line

That would make it possible to execute the script like this `lo_version=5.3.1.2 ./officeonlin-install.sh`

**Comment by aalaesar** [comment]
Hi there 😃, thank you for posting this issue.
I suppose you're speaking about the LibreOffice Online version downloaded with git while lo_version defines the Libre Office Version to compile. The variables to change the Lool version are documented [here](https://github.com/husisusi/officeonlin-install.sh#sources-status). But you still have to edit the script to change how it behave.

But you're right, the script is lacking a way to ingest external parameters.
All I can say is: it's on my list (with a lots of other points) but i'm out of free time to work on it until july. 😞 
But of course anyone is welcome to collaborate to the project. 😄 
Regards

**Comment by Gomez** [comment]
Thanks for the quick response!
Sure, i was just checking if its already done or planed :)

I will create a PR as soon as i have a working version. I will focus on make the version vars configureable from the outside.
