### ISSUE TITLE
failed reinstallation

### ISSUE THREAD

**Issue by fampla** [husisusi/officeonlin-install.sh#64]
hello, i have a problem (again).
after a complete installation and everything is working fine is startet the script again.
The problem was, that someone want to vacuum an need a socket. Long story short i did not install completely. "No problem" i thought and want to start the script again with the parameter lool_forcebuild cause at the lool there is the problem. But i said to me, that there is nothing to do because loolwd is already compiled and I'm not forced to recompile.

well but it is forced or forced to compile something.
i read there is ab problem with the parameters but is there any way to force anything?

thank you slevin7

**Comment by aalaesar** [comment]
Hi @Slevin7,
hmmm maybe bash misread the value ?
how lool_forcebuild has been set ?
should be `lool_forcebuild=true` no caps, no space 
you can try to run the script with bash -x to get more verbosity

Regards

**Comment by slevin-7** [comment]
well it is set like yours. with no nothing and it doesn´t force any build

so, i mv /opt/online to /opt/online-orig and now it recompile so this is done, but the parameter does not work at all.

**Comment by Kassiematis** [comment]
I have tested `lool_forcebuild=true` 2 times after each other and it works as it is supposed to.

**Comment by slevin-7** [comment]
It is strange I really had no Idea what went wrong.
i tried again after i rename the folder and now it works like a charm with lool_forcebuild=true.
First i thought i my mispelled something so i tried with the arrow up and it worked again.
Really no idea.
I think this could be closed.
