### ISSUE TITLE
upgrade feature

### ISSUE THREAD

**Issue by hostingnuggets** [husisusi/officeonlin-install.sh#66]
Hi,

it would be nice if your script has an upgrade feature in order to upgrade an existing installation which has been installed using this very same script...

Cheers!

**Comment by Kassiematis** [comment]
The script checks the different versions of poco, libreoffice and libreoffice online and update them when necessary.

**Comment by hostingnuggets** [comment]
Thanks, I am testing this right now. It would be a good idea to mention in the README that your script also does an upgrade if necessary as it is not so obvious.

**Comment by hostingnuggets** [comment]
I just ran `sudo officeonline-install.sh` as you suggested in order to upgrade my installation (Debian 8.7) and unfortunately it already failed around 15 minutes later with the following errors:

```
make: Entering directory '/opt/online'
make  all-recursive
make[1]: Entering directory '/opt/online'
Making all in .
make[2]: Entering directory '/opt/online'
  CXX      common/Seccomp.o
  CXX      common/Log.o
  CXX      common/MessageQueue.o
  CXX      common/SigUtil.o
  CXX      common/SpookyV2.o
  CXX      common/Unit.o
  CXX      common/UnitHTTP.o
  CXX      common/Util.o
/bin/bash: net/.deps/.dirstamp: Permission denied
Makefile:852: recipe for target 'net/.deps/.dirstamp' failed
make[2]: *** [net/.deps/.dirstamp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/opt/online'
Makefile:1719: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/online'
make: *** [all] Error 2
Makefile:731: recipe for target 'all' failed
make: Leaving directory '/opt/online'
grep: /etc/sudoers.d: Is a directory
rm: missing operand
Try 'rm --help' for more information.
```

Any ideas what's wrong? I am using the latest version of your script as I just cloned it today.

**Comment by aalaesar** [comment]
Hi
could be a Loolwsd build issue.
if you kept default configuration it compile from the latest commit of the master branch (not really safe 😕 )
Have you try running it again ? Still Not working ?
Can you attach the log file located in /tmp ?
Regards

**Comment by hostingnuggets** [comment]
@aalaesar as you recommended I ran your script again and now it went through everything and started the loolwsd service. It went quite fast so I am not 100% sure it really upgraded my installation. The About CODE page in a document online gives me the following version info:

```
This version of LibreOffice Online is powered by

LOOLWSD
master.. (git hash: 073b582)

LOKit
LibreOfficeDev 5.4.0.0.alpha0 (git hash: 2b3e1ce)
```
What do you think here, did the upgrade work? are should I be seeing other version numbers?

**Comment by aalaesar** [comment]
Right now the latest commit hash on master is indeed [073b582](https://github.com/LibreOffice/online/commit/073b58269b1fd63f946f3b7ba7b8b11754e5092c)
so yes, the "upgrade" (which is more like a replacement) worked 😉
do you have all the Online features available ?

**Comment by hostingnuggets** [comment]
:+1: Indeed you are right, I am using the latest commit of online.git and which was 12 hours ago and the latest commit of libreoffice's core. I am surprised that the last commit of the core of libreoffice is 3 month ago, that explains why I didn't have to wait a few hours for your update script to finish as I installed it around 2 months ago.
By the way at the upgrade I noticed that the config file `/opt/online/loolwsd.xml` got overwritten so I had to reconfigure my custom settings (just the hosts which are allowed in fact).
I suppose all the features are available but I am not really aware if there are any special new features...

**Comment by Ark74** [comment]
Are you using root?

Seems you can't remove previous installation files.

El 30 de mayo de 2017 3:24:01 PM CDT, Hosting Nuggets <notifications@github.com> escribió:
>I just ran `sudo officeonline-install.sh` as you suggested in order to
>upgrade my installation (Debian 8.7) and unfortunately it already
>failed around 15 minutes later with the following errors:
>
>```
>make: Entering directory '/opt/online'
>make  all-recursive
>make[1]: Entering directory '/opt/online'
>Making all in .
>make[2]: Entering directory '/opt/online'
>  CXX      common/Seccomp.o
>  CXX      common/Log.o
>  CXX      common/MessageQueue.o
>  CXX      common/SigUtil.o
>  CXX      common/SpookyV2.o
>  CXX      common/Unit.o
>  CXX      common/UnitHTTP.o
>  CXX      common/Util.o
>/bin/bash: net/.deps/.dirstamp: Permission denied
>Makefile:852: recipe for target 'net/.deps/.dirstamp' failed
>make[2]: *** [net/.deps/.dirstamp] Error 1
>make[2]: *** Waiting for unfinished jobs....
>make[2]: Leaving directory '/opt/online'
>Makefile:1719: recipe for target 'all-recursive' failed
>make[1]: *** [all-recursive] Error 1
>make[1]: Leaving directory '/opt/online'
>make: *** [all] Error 2
>Makefile:731: recipe for target 'all' failed
>make: Leaving directory '/opt/online'
>grep: /etc/sudoers.d: Is a directory
>rm: missing operand
>Try 'rm --help' for more information.
>```
>
>Any ideas what's wrong? I am using the latest version of your script as
>I just cloned it today.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/husisusi/officeonlin-install.sh/issues/66#issuecomment-304997184

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by hostingnuggets** [comment]
@Ark74 I am using sudo so in theory I should be allowed to remove anything.

**Comment by aalaesar** [comment]
closed by #69 ?
with latest tag as default instead of latest commit,, Broken build **_should_** append much more less frequently

**Comment by Ark74** [comment]
Hi!
I'm testing this too with the latest commit (4e31b96), but for some reason i can't _upgrade_ .

The same script has been run on a clean install and on a previous release installed.
With different results.

**Clean install:** 
LOOLWSD
2.1.2 (git hash: 4f4593a)
LOKit
Collabora OfficeDev 5.3-17 (git hash: 7daad24)

**Upgrade install:**
LOOLWSD
master.. (git hash: 1b5594f)
LOKit
LibreOfficeDev 5.3.0.3 (git hash: develop)

I find this part of the log interesting, (Lool-compilation.log )
```
From https://github.com/husisusi/online
   1b5594f..1c3eca6  master     -> origin/master
Error: distro/collabora/collabora-online-2-1 is not a valid branch.
Making clean in .
make[1]: Entering directory '/opt/online'
```
After 2 attempts i get the same behavior.
Could it be that some paths are hardcoded there?

**Comment by aalaesar** [comment]
Hi, I can see you are using https://github.com/husisusi/online instead of the default repo https://github.com/libreoffice/online
Is it intended ? 😀
TODO: add a check to verify the user have the correct repository
To fix ( for you) : (re)move /opt/online

What happened here:
- You have used the script a long time ago where it was still using the forked repo
- the current script search online a set for collabora in the default repo which is the official one now. It find a set of branches
- the script find a git repo in /opt/online then do not clone a new one but proceed to select the chosen branch
- as the old forked repo is obsolete, git fails to apply the changes and continue.

**Comment by Ark74** [comment]
Ohh!
I supposed something around those lines :smile: 

Hehehe.
I'll make the changes.
Thank you very much! :+1:

**Comment by quenenni** [comment]
I have a question about the upgrade process..

Let's say I have a working lool.
Then I re-run the script that finds a newer version and start the compilation process.

What happens to my working lool if the upgrade process fails? 

Will it mean that as soon as I restart the service loolwsd, nothing will work anymore?
Is it possible, in that case, to go easily back to the version I had working?
Or is the compilation of a newer version independent of the other ones?
Or is the solution to change the compilation folder (ie via a param) to be sure to keep untouched the one working?

**Comment by Kassiematis** [comment]
I have 2 servers where I can use one as test server. Also I can take a snapshot because I am running it on a VMware server. Running the script on a production server is not advised.

**Comment by quenenni** [comment]
I see your config is good for this situation, but how to do this if it's not a Vm?
I can also have a test server where I can try the upgrade first, but I'm forced to compile also on the prod server or is there another way to achieve that?

**Comment by Kassiematis** [comment]
First i compile, then i test as admin in owncloud, then i switch the url in the collabora online settings where the test server becomes the prod server. That only works if your Owncloud is not on the same server as the test and prod.

**Comment by quenenni** [comment]
I see.. Ok. Thanks for the tip.

What about if I change the values of these vars in the config file to point to another folder?
* lo_dir="/opt/libreoffice"
* poco_dir="/opt/poco-${poco_version}-all"
* lool_dir="/opt/online"
* and I guess also lool_configure_opts='' to set lool on another port

The compilation is a full one, but at least it doesn't touch the working one, correct?

And I should be able to rename the changed folder names to their classic one if the compilation succeeded, restart loolwsd service and it should work.. theoretically?

**Comment by Kassiematis** [comment]
I guess it could work. Never tried it before. Keep us posted.

**Comment by aalaesar** [comment]
Hi @quenenni 
This is a very good question. Thank you for asking.
There is some possibility to address each point in your question by a modification in the script(s)
We can add more conditions, change some testing process.

The quicker solution I can think would be to do the tests before the installation (that's not actually the case) but, in the script's  actual state : 
- The used configuration file /opt/online/loolwsd.xml is being overwritten **each build** with default values: allowed wopi hosts and others custom parameters will be erased. 
- The current test is very basic and do not guarantee that the application work as expected. Like the latest tag of the collabora-2.1 branch build successfully however the app is working very poorly with a lot of errors, but it could pass the current test as it is.

The best solution in my mind that will require more work but will greatly improve the script's value is **_packaging_**
Packaging will add a full new part to the process that will make the websocket server much more independent from the build process, and therefore safer.
By keeping the deb packages in a local folder, in case something go bad it will still be possible to reinstall very quickly an older, working, app. or build the app on a very strong server while installing it on another host,... or even on another architecture ( :wink: armhf :wink: )

**_NB:_** this is still possible to have **_right now_** multiple configurations files for the script that each contains variables pointing to a different set/commit/tag of a working version
Using the new --config option, you can select which one to use

**Comment by aalaesar** [comment]
... However, as I mentioned it in my post, releasing with packaging may require to add  a basic post configuration function on loolwsd.xml before.
So that's more work to do.
(every contribution is welcome 😄 )

**Comment by quenenni** [comment]
Well.. In some way, I like this way of doing thing.
Here is my idea.

I have my test & prod server and Lool is working on both of them.
I test the the new version on my test -> ok
I compile the new version on the prod server on separate folders.
  -> it worked -> I switch to the new one and keep the last one as a backup (still have to test that)
  -> it failed -> I still have my normal lool working and have time to find the problem

I can always keep one last version as backup in case the working one goes berserk.. 

The problem I see..
If all my lool have a problem, it's a long process to compile a new one (that can be mitigated if you have several lool server).

> -  The used configuration file /opt/online/loolwsd.xml is being overwritten each build with default values: allowed wopi hosts and others custom parameters will be erased.

Ok. but as I will use separate folders for the new compilation, that won't happen in my working lool folder.

The packaging idea is of course a good one. But I've never done one and to be honest, even if I'd like to be able to package stuff, I don't have time now to learn all that stuff (sorry).

One question though about packages..
If I understand correctly, to have access to packages mean that the Lool is already compiled (I think).
So, does it mean the compilation is only processor dependent ( a package for amd64 / i386 / armhf/ ..).
If it's the case, can't I compile a new version of Lool on another computer with the same processor (the test server ie) and then transfer the finished version to the prod server?
Can it work?

**Comment by quenenni** [comment]
I tried what I explained and i'm quite happy with the result.
I have 2 instances of lool running and so, I have a backup service ready to serve if the the new one fails.
And the next time I do a compilation, if it succeeds, I'll erase the old one. The current one becomes the old one and the just compiled one becomes the new one.

* As I couldn't find how to give a custom port for the compilation, I decided to do it the opposite way.
My active lool runs on a custom port and the new compilation will run on the default port.
Then I can change manually the port of the Loolwsd service as I see fit.
You just have to add the param --port in /etc/systemd/system/loolwsd.service
```
ExecStart=/opt/online2/loolwsd --o:sys_template_path=/opt/online2/systemplate --o:lo_template_path=/opt/libreoffice2/instdir  --o:child_root_path=/opt/online2/jails --port=9990
```
(replace /opt/online2 by whatever folder you put in the configuration file of this script)

* The difficulty was the LoolForKit service (a sub process of loolwsd) that compiles auto to run on port 9981.
If you do a new  compilation it will fail as it will try to start the new LoolForKit service on the same port.
I had to set a custom port.<br>
I saw in this file (/opt/online2/kit/ForKit.cpp) all the params available for loolforkit (replace /opt/online2 by whatever folder you put in the configuration file of this script)
```
else if (std::strstr(cmd, "--masterport=") == cmd)
```
I tried to use it in your config file, but was not recognized
```
lool_configure_opts='--masterport=9982'
```
I found a way, but to be able to do it, you must "git clone" online.git first (or start the compilation a first time) to be able to modify the file /opt/online2/common/Common.hpp (replace /opt/online2 by whatever folder you put in the configuration file of this script)
```
constexpr int DEFAULT_MASTER_PORT_NUMBER = 9982;
```
And it worked. LoolForKit process runs on port 9982.<br>
I looked bin/onlineBuild.sh for a possibility to set a param for that, but nothing found.
Any idea if it's possible in it's current state?

* The compilation create the file /lib/systemd/system/loolwsd.service and a copy here /etc/systemd/system/libreofficeonline.service

You must rename  /lib/systemd/system/loolwsd.service to anything else, create the symlink and delete the old file
```
systemctl stop loolwsd
mv /lib/systemd/system/loolwsd.service /lib/systemd/system/my_custom.service
ln -s /lib/systemd/system/my_custom.service /etc/systemd/system/my_custom.service
rm /etc/systemd/system/loolwsd.service
systemctl daemon-reload
systemctl start my_custom
```

* My officeonlin-install.sh-master/officeonline-install.cfg looks like this:
```
lo_dir="/opt/libreoffice2"
lool_dir="/opt/online2"
```
(no need to modify anything for poco)

**Comment by quenenni** [comment]
If you want to set a custom port for loolwsd and loolforkit processes at compilation time, in the file /opt/online2/common/Common.hpp (replace /opt/online2 by whatever folder you put in the configuration file of this script):
```
constexpr int DEFAULT_CLIENT_PORT_NUMBER = 9992;
constexpr int DEFAULT_MASTER_PORT_NUMBER = 9982;
```
With this, you don't have to put the --port param in the systemd service file, but you can put it there to change it if need be.

**Comment by quenenni** [comment]
About the upgrade system in general:

* I know there are advantages to packages, but I must say that to be able to have two instances of lool running including a backup instance is beautiful.
If you would like, in the future, to have lool available for the public, the packages are the good way. If you think it will be used mainly by sysadmin, this way is better as easier to set a lots of options. And it's less work.

Improvements I see for the script:
* Add the 2 parameters in the configuration file (ie: loolforkit_client_port & loolforkit_master_port) and if set, just after the git clone of online, do a sed on the file to change the port number.

* If you could move the warning dialog box that is showed after the git clone of libre office (that takes some time) to the beginning of the process, that would be nice. Several times I lost lots of hours because it was waiting for me to push enter.

* The part of the bin/onlineInstall.sh where you manage the /lib/systemd/system/loolwsd.service file is not good to manage upgrades. 
The problem now, if you are using my technique or for whatever reason you set another path for libreoffice or online, as the file already exists, it isn't changed.
Maybe test at the beginning of the script if the file already exists and if yes, ask if we want to keep it, upgrade it or create a new file.

If I didn't say that already, I'll repeat myself gladly.. You did a very nice job with this script.
I'm really happy I found it (by luck I must say. I think the missing 'e' at the name of your repo is not good for your visibility).
Thanks

**Comment by aalaesar** [comment]
Hi @quenenni,
Thank  you for your suggestions. 👍

- packaging is the way to go in my mind to obtain the most stateless  applications  possible. This requires  some research  and changing + improving mostly  the test phase. Today ways of enabling HA over micro services and allowing fast deployment  phases into pre-production and production  is mostly done with based container architectures and/or cloud computing, massively  using stateless  applications . And what you  described wanting here,  is mostly that. In the current state of the script, you are doing well to obtain it.

- I'll look  for some parameters to provide to the make file to change the port  on the build without  modifying  the code too much  because this may trigger git  and break  the script during the update phases.
- you can disable the messages with the config option `sh_interactive`  by setting it to false in the cfg file or with the `--config` command line option.
- the systemd's unit file is now overridden  when loolwsd  is (re)build. If you want to build a script  for setting a unit file elsewhere, contributions and Pull requests are welcome.😊 however this would not go in the direction of a stateless  application.

NB: we need a kanban  board now I think. I have noted a.lot of todo things.

**Comment by quenenni** [comment]
> * I'll look for some parameters to provide to the make file to change the port on the build without modifying the code too much because this may trigger git and break the script during the update phases

That's certainly the best way to do it.
I see what you mean by breaking the next git update.
Well, if you don't find a way to add a param somewhere, you can still do as I said and at the end of the script copy back the original file, but I know it's a temporary solution (or you can do a "git stash" before doing the "git pull").
I hope you'll find the right solution, but I don't think it will be easy as the compilation of Loolforkit seems to be a sub process started inside Loolwsd.
So, if not my solution, you'll have to change some file in the libreoffice git repo to achieve what you said, and it will have the same consequence.
That's my feeling about it, but I hope to be wrong.

> * you can disable the messages with the config option sh_interactive by setting it to false in the cfg file or with the --config command line option.

Ha yes.. I didn't pay attention to that variable.. Sorry

> * the systemd's unit file is now overridden when loolwsd is (re)build. If you want to build a script for setting a unit file elsewhere, contributions and Pull requests are welcome.😊 however this would not go in the direction of a stateless application.

Ok. I can add a param in officeonline-install.cfg (and other cfg files) for the service name you want if not the default one. It shouldn't be too difficult.
I'll try to do a pull request for that soon (and it should be ok .with whatever direction you are going with the script.. I think)

I noticed a strange effect from my last compilation.
In the script, in bin/onlineInstall.sh, you test if the file /etc/systemd/system/loolwsd.service exists and if not, you create a symlink.
So how is it possible I have a file and not a symlink in my systemd folder?
```
if [ ! -e /etc/systemd/system/loolwsd.service ]; then
  ln /lib/systemd/system/loolwsd.service /etc/systemd/system/loolwsd.service
fi
->
ls -l /lib/systemd/system/loolwsd.service 
-rw-r--r-- 2 root root 594 aoû 20 02:20 /lib/systemd/system/loolwsd.service
and
ls -l /etc/systemd/system/loolwsd.service
-rw-r--r-- 2 root root 594 aoû 20 02:20 /etc/systemd/system/loolwsd.service
```
(all my loowsd.service files were deleted before starting the new process and you can see the 2 files have the same creation time)

**Comment by Kassiematis** [comment]
As you can see there is a 2 in front of `2 root root 594` meaning that there are 2 files linked. Looks just like a normal file.
With `ln -s` you can create a softlink which will look like this.

`link -> /home/administrator/test/folder`

**Comment by quenenni** [comment]
Hooo.. Stupid me.
I'm so used to create them with the -s param that I didn't event think about that "not used" param in your code.. 
Thanks for your help.
