### ISSUE TITLE
Error Loolwsd

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#72]
For some reason if only Libreoffice gets compiled and not Loolwsd I can not start it.

Capability cap_sys_chroot is not set for the loolforkit program.| kit/ForKit.cpp:151
Capability cap_mknod is not set for the loolforkit program.| kit/ForKit.cpp:151
Capability cap_fowner is not set for the loolforkit program.| kit/ForKit.cpp:151

**Comment by aalaesar** [comment]
I was wondering if triggering a new build for core would impact Online.
Seems to be the case.
Are the errors coming from Loolwsd at startup or from the script itself ?

**Comment by Kassiematis** [comment]
The errors are from Loolwsd. Script ran fine.

> Selected Tag: 2.1.2-rc2 4b03b9b
> Loolwsd is already compiled and I'm not forced to recompile.
> Leaving here...
>

**Comment by Kassiematis** [comment]
I found this in the Makefile,

```
# After building loolforkit, set its capabilities as required. Do it
# already after a plain 'make' to allow for testing without
# installing. When building for packaging, no need for this, as the
# capabilities won't survive packaging anyway. Instead, handle it when
# installing the RPM or Debian package.

all-local: loolforkit ${abs_top_builddir}/jails $(SYSTEM_STAMP)
        @if test "$$BUILDING_FROM_RPMBUILD" != yes; then \
            sudo /sbin/setcap cap_fowner,cap_mknod,cap_sys_chroot=ep loolforkit; \
            sudo /sbin/setcap cap_sys_admin=ep loolmount; \
            echo "Set required capabilities"; \
        else \
            echo "Skipping capability setting"; \
        fi

```

**Comment by aalaesar** [comment]
to fix your current state, run the script with lool_forcebuild=true
until I figured out why this append (thank for the explanation)
Could do a quick fixon your side:
add after line 498
`   if $lo_forcebuild; then lool_forcebuild=true; fi`

**Comment by Kassiematis** [comment]
These 2 commands fixed it for me.

sudo /sbin/setcap cap_fowner,cap_mknod,cap_sys_chroot=ep /opt/online/loolforkit
sudo /sbin/setcap cap_sys_admin=ep /opt/online/loolmount

We could put this into the script.
