### ISSUE TITLE
ttf-mscorefonts-installer

### ISSUE THREAD

**Issue by Kassiematis** [husisusi/officeonlin-install.sh#82]
Running `sudo apt-get install ttf-mscorefonts-installer` and recompiling libreoffice gives you the following Microsoft fonts.

Andale_Mono.ttf
Arial_Black.ttf
Arial_Bold_Italic.ttf
Arial_Bold.ttf
Arial_Italic.ttf
Arial.ttf
Arial_Black.ttf
Comic_Sans_MS_Bold.ttf
Comic_Sans_MS.ttf
Courier_New_Bold.ttf
Courier_New_Bold_Italic.ttf
Courier_New_Bold_Italic.ttf
Courier_New_Bold.ttf
Courier_New_Italic.ttf
Courier_New.ttf
Georgia_Bold_Italic.ttf
Georgia_Bold.ttf
Georgia_Italic.ttf
Georgia.ttf
Impact.ttf
Times_New_Roman_Bold_Italic.ttf
Times_New_Roman_Bold.ttf
Times_New_Roman_Italic.ttf
Times_New_Roman.ttf
Trebuchet_MS_Bold_Italic.ttf
Trebuchet_MS_Bold.ttf
Trebuchet_MS_Italic.ttf
Trebuchet_MS.ttf
Verdana_Bold_Italic.ttf
Verdana_Bold.ttf
Verdana_Italic.ttf
Verdana.ttf
Webdings.ttf

Incorporating this in the script will be tricky because you have to accept an EULA at install.

You can ignore message `Can't drop privileges`

**Comment by aalaesar** [comment]
Hi there!
I'm not sure how this is an issue.
Is it a feature request ?

**Comment by Kassiematis** [comment]
Having Microsoft fonts standard on Ubuntu is very helpful for cross compatibility with office documents.

**Comment by aalaesar** [comment]
Is there an option to add to the configure script before compiling the core ?

**Comment by Kassiematis** [comment]
Do you mean? 
sudo apt-get install ttf-mscorefonts-installer
fc-cache -f -v

**Comment by Kassiematis** [comment]
found this for the EULA
```
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
sudo apt-get install ttf-mscorefonts-installer -y
```

**Comment by Kassiematis** [comment]
Will this work in the script?

if [ ! -f /usr/share/fonts/truetype/msttcorefonts/times.ttf ]; then
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
apt-get install ttf-mscorefonts-installer -y
fi

**Comment by Kassiematis** [comment]
Just tested and it works. Created a pull request.
