### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by mike2m** [husisusi/officeonlin-install.sh#84]
Hi,
Many thanks for the script!
All is set and the link is opened:
https://localhost:9980/loleaflet/dist/loleaflet.html?file_path=file:///opt/online/test/data/hello-world.odt
and
https://admin:password@localhost:9980/loleaflet/dist/admin/admin.html

problem occurred with the integration into owncloud v.9.1.6 (richdocument v.1.1.20):
1. in admin error Collabora Online: **Saved with error: Collabora Online should use the same protocol as the server installation.**
2. in front (office) error: Well, this is embarrassing, we cannot connect to your document. Please try again.

**Comment by Kassiematis** [comment]
You should check /var/log/loolwsd.log. Did you change the apache settings?

Check this issue.

https://github.com/husisusi/officeonlin-install.sh/issues/61

**Comment by mike2m** [comment]
Hi,
root@lof:/var/log# cat loolwsd.log
kit-01717-00523 09:40:29.342766 [ loolkit ] INF  Initializing kit. Local time: Thu 2017-06-29 16:40:29+0700. Log level is [8].| common/Log.cpp:199
kit-01717-00523 09:40:29.342819 [ loolkit ] DBG  Process started.| kit/Kit.cpp:1614
kit-01717-00523 09:40:29.342865 [ loolkit ] INF  Jail path: /opt/online/jails/U2v0uhIYnu8tqLYw/| kit/Kit.cpp:1628
kit-01717-00523 09:40:29.343072 [ loolkit ] DBG  symlink("../../lo","/opt/online/jails/U2v0uhIYnu8tqLYw/opt/libreoffice/instdir")| kit/Kit.cpp:269
kit-01717-00523 09:40:29.371907 [ loolkit ] TRC  skip redundant paths share/Scripts| kit/Kit.cpp:179
kit-01717-00523 09:40:29.372045 [ loolkit ] TRC  skip redundant paths share/template| kit/Kit.cpp:179
kit-01717-00523 09:40:29.374579 [ loolkit ] TRC  skip redundant paths share/config/wizard| kit/Kit.cpp:179
kit-01717-00523 09:40:29.411842 [ loolkit ] TRC  skip redundant paths share/gallery| kit/Kit.cpp:179
kit-01717-00523 09:40:29.412962 [ loolkit ] TRC  skip redundant paths share/basic| kit/Kit.cpp:179
kit-01717-00523 09:40:29.413886 [ loolkit ] TRC  skip redundant paths program/wizards| kit/Kit.cpp:179
kit-01717-00523 09:40:29.421172 [ loolkit ] TRC  skip redundant paths sdk| kit/Kit.cpp:179
kit-01717-00523 09:40:29.441710 [ loolkit ] DBG  Initialized jail files.| kit/Kit.cpp:1685
kit-01717-00523 09:40:29.441804 [ loolkit ] INF  chroot("/opt/online/jails/U2v0uhIYnu8tqLYw/")| kit/Kit.cpp:1709
kit-01717-00523 09:40:29.441838 [ loolkit ] TRC  Capabilities first: = cap_fowner,cap_sys_chroot,cap_mknod+ep| kit/Kit.cpp:235
kit-01717-00523 09:40:29.441864 [ loolkit ] TRC  Capabilities now: = cap_fowner,cap_mknod+ep| kit/Kit.cpp:252
kit-01717-00523 09:40:29.441873 [ loolkit ] TRC  Capabilities first: = cap_fowner,cap_mknod+ep| kit/Kit.cpp:235
kit-01717-00523 09:40:29.441882 [ loolkit ] TRC  Capabilities now: = cap_fowner+ep| kit/Kit.cpp:252
kit-01717-00523 09:40:29.441890 [ loolkit ] TRC  Capabilities first: = cap_fowner+ep| kit/Kit.cpp:235
kit-01717-00523 09:40:29.441898 [ loolkit ] TRC  Capabilities now: =| kit/Kit.cpp:252
kit-01717-00523 09:40:29.441905 [ loolkit ] DBG  Initialized jail nodes, dropped caps.| kit/Kit.cpp:1726
kit-01717-00523 09:40:29.471917 [ loolkit ] TRC  Install seccomp filter successfully.| common/Seccomp.cpp:212
kit-01717-00523 09:40:29.471953 [ loolkit ] INF  Process is ready.| kit/Kit.cpp:1768
kit-01717-00523 09:40:29.471975 [ loolkit ] DBG  Connecting to Master 127.0.0.1:9981| kit/Kit.cpp:1789
kit-01717-00523 09:40:29.472696 [ loolkit ] INF  SocketProcessor [child_ws_1717] starting.| common/IoUtil.cpp:50
kit-01721-00523 09:40:30.374899 [ loolkit ] INF  Initializing kit. Local time: Thu 2017-06-29 16:40:30+0700. Log level is [8].| common/Log.cpp:199
kit-01721-00523 09:40:30.374955 [ loolkit ] DBG  Process started.| kit/Kit.cpp:1614
kit-01721-00523 09:40:30.374994 [ loolkit ] INF  Jail path: /opt/online/jails/zZ8Cv36WfOwTFlP8/| kit/Kit.cpp:1628
kit-01721-00523 09:40:30.375164 [ loolkit ] DBG  symlink("../../lo","/opt/online/jails/zZ8Cv36WfOwTFlP8/opt/libreoffice/instdir")| kit/Kit.cpp:269
kit-01721-00523 09:40:30.404265 [ loolkit ] TRC  skip redundant paths share/Scripts| kit/Kit.cpp:179
kit-01721-00523 09:40:30.404434 [ loolkit ] TRC  skip redundant paths share/template| kit/Kit.cpp:179
kit-01721-00523 09:40:30.406984 [ loolkit ] TRC  skip redundant paths share/config/wizard| kit/Kit.cpp:179
kit-01721-00523 09:40:30.444168 [ loolkit ] TRC  skip redundant paths share/gallery| kit/Kit.cpp:179
kit-01721-00523 09:40:30.445246 [ loolkit ] TRC  skip redundant paths share/basic| kit/Kit.cpp:179
kit-01721-00523 09:40:30.446118 [ loolkit ] TRC  skip redundant paths program/wizards| kit/Kit.cpp:179
kit-01721-00523 09:40:30.453271 [ loolkit ] TRC  skip redundant paths sdk| kit/Kit.cpp:179
kit-01721-00523 09:40:30.474578 [ loolkit ] DBG  Initialized jail files.| kit/Kit.cpp:1685
kit-01721-00523 09:40:30.474708 [ loolkit ] INF  chroot("/opt/online/jails/zZ8Cv36WfOwTFlP8/")| kit/Kit.cpp:1709
kit-01721-00523 09:40:30.474744 [ loolkit ] TRC  Capabilities first: = cap_fowner,cap_sys_chroot,cap_mknod+ep| kit/Kit.cpp:235
kit-01721-00523 09:40:30.474758 [ loolkit ] TRC  Capabilities now: = cap_fowner,cap_mknod+ep| kit/Kit.cpp:252
kit-01721-00523 09:40:30.474774 [ loolkit ] TRC  Capabilities first: = cap_fowner,cap_mknod+ep| kit/Kit.cpp:235
kit-01721-00523 09:40:30.474783 [ loolkit ] TRC  Capabilities now: = cap_fowner+ep| kit/Kit.cpp:252
kit-01721-00523 09:40:30.474792 [ loolkit ] TRC  Capabilities first: = cap_fowner+ep| kit/Kit.cpp:235
kit-01721-00523 09:40:30.474800 [ loolkit ] TRC  Capabilities now: =| kit/Kit.cpp:252
kit-01721-00523 09:40:30.474807 [ loolkit ] DBG  Initialized jail nodes, dropped caps.| kit/Kit.cpp:1726
kit-01721-00523 09:40:30.506007 [ loolkit ] TRC  Install seccomp filter successfully.| common/Seccomp.cpp:212
kit-01721-00523 09:40:30.506063 [ loolkit ] INF  Process is ready.| kit/Kit.cpp:1768
kit-01721-00523 09:40:30.506088 [ loolkit ] DBG  Connecting to Master 127.0.0.1:9981| kit/Kit.cpp:1789
kit-01721-00523 09:40:30.506963 [ loolkit ] INF  SocketProcessor [child_ws_1721] starting.| common/IoUtil.cpp:50
kit-01717-00523 09:40:31.357321 [ loolkit ] TRC  Got frame: TEXT 4 bytes: 'exit'| ./common/LOOLWebSocket.hpp:125
kit-01717-00523 09:40:31.357402 [ loolkit ] DBG  child_ws_1717: recv [exit].| kit/Kit.cpp:1810
kit-01717-00523 09:40:31.357428 [ loolkit ] TRC  Setting TerminationFlag due to 'exit' command from parent.| kit/Kit.cpp:1842
kit-01717-00523 09:40:31.357458 [ loolkit ] INF  SocketProcessor [child_ws_1717]: Stop flagged.| common/IoUtil.cpp:69
kit-01717-00523 09:40:31.357466 [ loolkit ] INF  SocketProcessor [child_ws_1717] finished. stop: true, n: 4, payload size: 0, flags: 81| common/IoUtil.cpp:b7
kit-01717-00523 09:40:31.357543 [ loolkit ] INF  Process finished.| kit/Kit.cpp:1910

**Comment by Kassiematis** [comment]
Are you using ssl with Owncloud?

**Comment by husisusi** [comment]
@mike2m make DNS record and install your certificate on your Proxy and loolwsd.xml.
Edit your  loolwsd.xml to allow access from your Owncloud.
Restart loolwsd and your Proxy.
 That's all!
