### ISSUE TITLE
certificate permissions and duration

### ISSUE THREAD

**Issue by keros** [husisusi/officeonlin-install.sh#89]
Hi

On about line 600 the self signed certificate chain is createt with openssl.
It maybe would be a good idea to create the certificates for more than one year (10 sounds better in my head).
Also the permissions on the keyfile should be set to 600 and the owner should be set to "lool".
The current default ist 644 which allows everyone on the system to read the keyfile.

**Comment by Kassiematis** [comment]
10 years is a bit long for a self signed certificate. It would be better to get a certificate that is signed by a CA. (which is also max 3 or 5 years)
Changing it to 3 years is probably a better compromise.

I have created a pull request.

**Comment by keros** [comment]
Looks good for me thx

**Comment by Kassiematis** [comment]
Pull request has been merged. Deleting/moving the certificates files will cause script to create new ones.
Don't forget this command.
cat /etc/loolwsd/ca-chain.cert.pem >> /var/www/owncloud/resources/config/ca-bundle.crt (or wherever your owncloud is installed)
