### ISSUE TITLE
bind to 127.0.0.1:9980 only

### ISSUE THREAD

**Issue by ghost** [husisusi/officeonlin-install.sh#95]
Hi Devs.

Is it possible to bind loolwsd to ip 127.0.0.1 only? Did not find a setting like this.

thanks and cheers
t.

**Comment by Kassiematis** [comment]
Edit /opt/online/loolwsd.xml.

```
<storage desc="Backend storage">
        <filesystem allow="false" />
        <wopi desc="Allow/deny wopi storage. Mutually exclusive with webdav." allow="true">
            <host desc="Regex pattern of hostname to allow or deny." allow="true">localhost</host>
            <host desc="Regex pattern of hostname to allow or deny." allow="true">127\.0\.0\.1</host>
            <max_file_size desc="Maximum document size in bytes to load. 0 for unlimited." type="uint">0</max_file_size>
        </wopi>
        <webdav desc="Allow/deny webdav storage. Mutually exclusive with wopi." allow="false">
            <host desc="Hostname to allow" allow="false">localhost</host>
        </webdav>
</storage>
```


Hopefully this will solve your question.

**Comment by ghost** [comment]
Thanks for your quick answer. It does not solve my issue but leads to more understanding of the software. I thought i could make loolswd listen to 127.0.0.1 only and still have the opportunity to restrict access to hostnames and ip addresses. But that seems not possible? The use case is an apache as proxy in front of loolwsd.

thanks and cheers
t.

**Comment by Kassiematis** [comment]
Have a look at this issue #93. It might be useful.
